### ISSUE TITLE
Fate Command is broken

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2754] opened 2022-06-03 12:03 UTC
**Describe the bug**
Many changes have been made to the `fate` shell command and now it doesn't work properly. 

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 2.1
 - OS: Ubuntu 18
 - Others: Hadoop 3.2.2 & apache-zookeeper-3.6.3

**To Reproduce**
Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):
1. Run CI from accumulo-testing for 10 minutes: `./bin/cingest createtable` and then `./bin/cingest ingest`
2. Run the Shell cmd: `compact -t ci`
3. Run the Shell cmd: `listcompactions`. Make sure there is at least one "USER" compaction.
4. Run the Shell cmd: `fate -list` or `fate -print`. There should be the User Compact FATE operation printed but you only get `0 transactions`
5. From ZK Shell, `ls /accumulo/<instance_id>/fate`
[zk: localhost:2181(CONNECTED) 3] ls /accumulo/363c7563-bd35-448a-9dbc-dc6ef18cd819/fate
[tx_291329b4af233519]
6. In the log directory: `grep "291329b4af233519" *.log` to the TX seeded in the manager log.

**Expected behavior**
The user compaction Fate TX should be printed in the shell.

<pre>
root@uno> compact -t ci
2022-06-03T07:39:29,891 [shell.Shell] INFO : Compaction of table ci started for given range
root@uno> fate -list
2022-06-03T07:39:31,775 [conf.SiteConfiguration] INFO : Found Accumulo configuration on classpath at /home/mpmill4/workspace/uno/install/accumulo-2.1.0-SNAPSHOT/conf/accumulo.properties
 0 transactions
root@uno> listcompactions 
 SERVER               | AGE       | TYPE  | REASON | READ  | WROTE | TABLE           | TABLET                                   | INPUT | OUTPUT                              | ITERATORS | ITERATOR OPTIONS
       localhost:9997 |   5s424ms | MAJOR | SYSTEM |  921K |  902K |              ci | 1;733333333333333e;6cccccccccccccd7      |     4 |        /1/t-000004m/C000027e.rf_tmp |        [] | {}
       localhost:9997 |    5s23ms |  FULL |   USER |  840K |  829K |              ci | 1;533333333333333b;4cccccccccccccd4      |     8 |        /1/t-000004h/A000027f.rf_tmp |        [] | {}
       localhost:9997 |   3s125ms |  FULL |   USER |  547K |  540K |              ci | 1<;79999999999999a5                      |     7 |   /1/default_tablet/A000027g.rf_tmp |        [] | {}
      localhost:10000 |   5s243ms |  FULL |   USER |  897K |  893K |              ci | 1;0cccccccccccccce;0666666666666667      |     5 |        /1/t-0000046/A000022u.rf_tmp |        [] | {}
      localhost:10000 |   1s225ms |  FULL |   USER |  208K |  206K |              ci | 1;1333333333333335;0cccccccccccccce      |     7 |        /1/t-0000047/A000022v.rf_tmp |        [] | {}
root@uno> fate -list
2022-06-03T07:39:44,128 [conf.SiteConfiguration] INFO : Found Accumulo configuration on classpath at /home/mpmill4/workspace/uno/install/accumulo-2.1.0-SNAPSHOT/conf/accumulo.properties
 0 transactions
[zk: localhost:2181(CONNECTED) 3] ls /accumulo/363c7563-bd35-448a-9dbc-dc6ef18cd819/fate
[tx_291329b4af233519]
08:00:34 {main} ~/workspace/uno/install/logs/accumulo$ grep 291329b4af233519 *.log
manager_ip-10-113-14-231-06-03-22-07-1.log:2022-06-03T07:39:29,881 [fate.Fate] INFO : Seeding FATE[291329b4af233519] TABLE_COMPACT Compact table (1) with config []
manager_ip-10-113-14-231-06-03-22-07-1.log:2022-06-03T07:39:29,895 [zookeeper.DistributedReadWriteLock] INFO : Added lock entry 0 userData 291329b4af233519 lockType READ
manager_ip-10-113-14-231-06-03-22-07-1.log:2022-06-03T07:39:29,896 [tableOps.Utils] INFO : namespace +default (291329b4af233519) locked for read operation: COMPACT
manager_ip-10-113-14-231-06-03-22-07-1.log:2022-06-03T07:39:29,904 [zookeeper.DistributedReadWriteLock] INFO : Added lock entry 0 userData 291329b4af233519 lockType READ
manager_ip-10-113-14-231-06-03-22-07-1.log:2022-06-03T07:39:29,905 [tableOps.Utils] INFO : table 1 (291329b4af233519) locked for read operation: COMPACT
</pre>

**Comment by Manno15** [comment] 2022-06-03 12:16
Is this reproduced with the changes in PR #2215? That also refactors how
the Fate command works and may or may not have this same issue. When I was
originally testing, I found that timing was important for the fate -list
command. I usually added a timer during table creation in order to see a
fate transaction taking place. Otherwise, the transaction finished before I
could print/ do other fate commands to it.

**Comment by milleruntime** [comment] 2022-06-03 13:32
> Is this reproduced with the changes in PR [#2215](https://github.com/apache/accumulo/pull/2215)?

I haven't tested it with your branch but if it is up to date then I think it would have the same problem.

> When I was originally testing, I found that timing was important for the fate -list command. I usually added a timer during table creation in order to see a fate transaction taking place. Otherwise, the transaction finished before I could print/ do other fate commands to it.

Right, it is tricky to get the timing. I found it helps if you use the `SlowIterator` on a compaction. This requires the test jar and can be done using these commands:
<pre>
config -t ci -s table.iterator.majc.slow=1,org.apache.accumulo.test.functional.SlowIterator
config -t ci -s table.iterator.majc.slow.opt.sleepTime=5
</pre>

It helps to cancel compactions on the table first too then run a user compaction. Fate TX will only be created for user initiated compaction. I just confirmed this again on main using the `SlowIterator`:
<pre>
[zk: localhost:2181(CONNECTED) 2] ls /accumulo/af1770d1-ffa1-4373-95f9-d715b11d70dd/fate 
[tx_50704e650c56e804]
[zk: localhost:2181(CONNECTED) 3] get /accumulo/af1770d1-ffa1-4373-95f9-d715b11d70dd/fate/tx_50704e650c56e804 
IN_PROGRESS
root@uno ci> fate -print 50704e650c56e804
2022-06-03T09:26:32,409 [conf.SiteConfiguration] INFO : Found Accumulo configuration on classpath at /home/mpmill4/workspace/uno/install/accumulo-2.1.0-SNAPSHOT/conf/accumulo.properties
 0 transactions
root@uno ci> fate -print 50704e650c56e804
2022-06-03T09:30:27,019 [conf.SiteConfiguration] INFO : Found Accumulo configuration on classpath at /home/mpmill4/workspace/uno/install/accumulo-2.1.0-SNAPSHOT/conf/accumulo.properties
 0 transactions
root@uno ci> fate -print 
2022-06-03T09:30:31,987 [conf.SiteConfiguration] INFO : Found Accumulo configuration on classpath at /home/mpmill4/workspace/uno/install/accumulo-2.1.0-SNAPSHOT/conf/accumulo.properties
 0 transactions
root@uno ci> fate -list
2022-06-03T09:30:34,832 [conf.SiteConfiguration] INFO : Found Accumulo configuration on classpath at /home/mpmill4/workspace/uno/install/accumulo-2.1.0-SNAPSHOT/conf/accumulo.properties
 0 transactions
</pre>
</pre>

**Comment by milleruntime** [comment] 2022-06-03 14:40
I think there is a bigger issue going on here, unrelated to the Fate Command. I setup a cluster after I reverted back to before #2569 was merged and it works better. I am able to see FATE TXs, even with the NPE that was fixed in #2738. I think there is an unresolved issue related to the ZK prop store refactor in #2569 that is causing the Fate Command to not work properly.

**Comment by mjwall** [comment] 2022-06-03 14:46
FWIW, I just pulled in #2569 to my 1.10 branch and immediately got this running `mvn clean verify`
```
[INFO] Apache Accumulo Maven Plugin ....................... SKIPPED                                                                                                                                                                                                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  42.187 s                                                                                                                                                                                                                                                                                                
[INFO] Finished at: 2022-06-03T14:14:52Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M4:test (default-test) on project accumulo-fate: There are test failures.
[ERROR]
[ERROR] Please refer to /home/mjwall/src/oss/accumulo-mjwall-1.10/fate/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/mjwall/src/oss/accumulo-mjwall-1.10/fate && /home/mjwall/opt/jdk-11.0.14/bin/java -Xmx1G -jar /home/mjwall/src/oss/accumulo-mjwall-1.10/fate/target/surefire/surefirebooter5780153386212598703.jar /home/mjwall/src/oss/accumulo-mjwall-1.10/fate/target/surefire 2022-06-03T14-14-30
_316-jvmRun6 surefire16622590161902785932tmp surefire_88617873131608458531tmp
[ERROR] Process Exit Code: 0
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?                                                                                                                                          
[ERROR] Command was /bin/sh -c cd /home/mjwall/src/oss/accumulo-mjwall-1.10/fate && /home/mjwall/opt/jdk-11.0.14/bin/java -Xmx1G -jar /home/mjwall/src/oss/accumulo-mjwall-1.10/fate/target/surefire/surefirebooter5780153386212598703.jar /home/mjwall/src/oss/accumulo-mjwall-1.10/fate/target/surefire 2022-06-03T14-14-30
_316-jvmRun6 surefire16622590161902785932tmp surefire_88617873131608458531tmp
[ERROR] Process Exit Code: 0
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.awaitResultsDone(ForkStarter.java:513)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.runSuitesForkPerTestSet(ForkStarter.java:460)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:301)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:249)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1217)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1063)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:889)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:301)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:211)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:165)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:157)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:121)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:127)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:294)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR] Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/mjwall/src/oss/accumulo-mjwall-1.10/fate && /home/mjwall/opt/jdk-11.0.14/bin/java -Xmx1G -jar /home/mjwall/src/oss/accumulo-mjwall-1.10/fate/target/surefire/surefirebooter5780153386212598703.jar /home/mjwall/src/oss/accumulo-mjwall-1.10/fate/target/surefire 2022-06-03T14-14-30
_316-jvmRun6 surefire16622590161902785932tmp surefire_88617873131608458531tmp
[ERROR] Process Exit Code: 0
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:690)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.access$600(ForkStarter.java:118)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter$2.call(ForkStarter.java:447)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter$2.call(ForkStarter.java:423)
[ERROR]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[ERROR]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[ERROR]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :accumulo-fate
```

Rerunning `mvn clean verify` passed successfully

**Comment by EdColeman** [comment] 2022-06-03 14:51
https://github.com/apache/accumulo/pull/2569 was specifically written with 2.1 - I'd be surprised if it compiled against 1.10 and even more astonished it it worked at all.

**Comment by mjwall** [comment] 2022-06-03 14:54
You are right, I meant #2708.  Ignore this

**Comment by EdColeman** [comment] 2022-06-03 15:38
I do get an exception in a tserver log - if I try to run the fate -print command with -e option to the shell. The error is intermitent, and if I log into the shell, run fate -print, log back out of the shell, it seems to work passing it as a command

```
$ accumulo shell -u root -p uno -e 'fate -print'

2022-06-03T15:29:00,326 [shell.Shell] ERROR: java.lang.RuntimeException: Unexpected exception thrown
```
# A full trace from tserver log
<details>
  <summary>Click to expand</summary>
  
2022-06-03T15:27:40,187 [client.ClientServiceHandler] ERROR: ThriftSecurityException
org.apache.accumulo.core.clientImpl.thrift.ThriftSecurityException: null
        at org.apache.accumulo.server.security.SecurityOperation.authenticate(SecurityOperation.java:207) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.server.security.AuditedSecurityOperation.authenticate(AuditedSecurityOperation.java:730) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.server.security.SecurityOperation.authenticateUser(SecurityOperation.java:219) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.server.client.ClientServiceHandler.authenticate(ClientServiceHandler.java:153) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.server.client.ClientServiceHandler.executeAdminOperation(ClientServiceHandler.java:473) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.apache.accumulo.core.trace.TraceUtil.lambda$wrapService$0(TraceUtil.java:206) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at com.sun.proxy.$Proxy36.executeAdminOperation(Unknown Source) ~[?:?]
        at org.apache.accumulo.core.clientImpl.thrift.ClientService$Processor$executeAdminOperation.getResult(ClientService.java:3134) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.clientImpl.thrift.ClientService$Processor$executeAdminOperation.getResult(ClientService.java:3113) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38) ~[libthrift-0.16.0.jar:0.16.0]
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38) ~[libthrift-0.16.0.jar:0.16.0]
        at org.apache.thrift.TMultiplexedProcessor.process(TMultiplexedProcessor.java:138) ~[libthrift-0.16.0.jar:0.16.0]
        at org.apache.accumulo.server.rpc.TimedProcessor.process(TimedProcessor.java:54) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:524) ~[libthrift-0.16.0.jar:0.16.0]
        at org.apache.accumulo.server.rpc.CustomNonBlockingServer$CustomFrameBuffer.invoke(CustomNonBlockingServer.java:129) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.thrift.server.Invocation.run(Invocation.java:18) ~[libthrift-0.16.0.jar:0.16.0]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:834) ~[?:?]

</details>

**Comment by EdColeman** [comment] 2022-08-02 16:37
Fixed with #2755

**Closed by EdColeman** 2022-08-02 16:37 UTC
Labels: blocker, bug

**Comment by Manno15** [comment] 2022-10-11 09:21
It depends on what the issue is. #2215 did fix some issues after I
initially resolved some merge conflicts. Unsure on how new this particular
bug is though.

**Comment by EdColeman** [comment] 2022-10-11 15:50
I believe that it was "fixed" at the time - but since then the FATE command and the tests have moved to Admin - so that could have either introduced something new, invalidated the fix or maybe not.
