### ISSUE TITLE
Broken or Flaky test: HalfDeadTServerIT.testRecover

### ISSUE THREAD

**Issue by DomGarguilo** [apache/accumulo#2613] opened 2022-04-07 14:41 UTC
**Test name(s)**
 - HalfDeadTServerIT.testRecover

**Describe the failure observed**
It looks like this test has failed via timeout in the last two builds. It looks like it has failed at least once before as well but twice in a row seems more than a coincidence.

The failing runs:
- [April 7 2022](https://ci-builds.apache.org/job/Accumulo/job/main/311/org.apache.accumulo$accumulo-test/testReport/org.apache.accumulo.test.functional/HalfDeadTServerIT/testRecover/)
- [April 6 2022](https://ci-builds.apache.org/job/Accumulo/job/main/org.apache.accumulo$accumulo-test/310/testReport/junit/org.apache.accumulo.test.functional/HalfDeadTServerIT/testRecover/)
- [February 5 2022](https://ci-builds.apache.org/job/Accumulo/job/1.x-Hadoop2/org.apache.accumulo$accumulo-test/52/testReport/org.apache.accumulo.test.functional/HalfDeadTServerIT/testRecover/)

It looks like the all timed out in the same spot:
<details>
  <summary>Click to expand!</summary>
  
```
Caused by: org.junit.jupiter.api.AssertTimeout$ExecutionTimeoutException: Execution timed out in thread junit-timeout-thread-7
	at java.base@11.0.12/java.lang.Object.wait(Native Method)
	at java.base@11.0.12/java.lang.Object.wait(Object.java:328)
	at java.base@11.0.12/java.lang.ProcessImpl.waitFor(ProcessImpl.java:495)
	at app//org.apache.accumulo.test.functional.HalfDeadTServerIT.test(HalfDeadTServerIT.java:218)
	at app//org.apache.accumulo.test.functional.HalfDeadTServerIT.testRecover(HalfDeadTServerIT.java:143)
	at java.base@11.0.12/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.12/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.12/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.12/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at app//org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at app//org.apache.accumulo.harness.Timeout$$Lambda$501/0x0000000800358840.get(Unknown Source)
	at app//org.junit.jupiter.api.AssertTimeout.lambda$assertTimeoutPreemptively$4(AssertTimeout.java:138)
	at app//org.junit.jupiter.api.AssertTimeout$$Lambda$442/0x00000008002ad840.call(Unknown Source)
	at java.base@11.0.12/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.12/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base@11.0.12/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base@11.0.12/java.lang.Thread.run(Thread.java:834)
```

</details>

Which is this line in the test:
https://github.com/apache/accumulo/blob/d454afd39c91ee0a1ab267e0caafc52254d209b0/test/src/main/java/org/apache/accumulo/test/functional/HalfDeadTServerIT.java#L218

**Testing Environment:**
 - First commit known to fail: bbae5c6da9dbfa25b4dedf2e79e9a969497d217c
 - Other commits that are failing: d454afd39c91ee0a1ab267e0caafc52254d209b0 and 6d1a9de2f6cba5a3fa5dcd0840cbf0371039eb79

**What have you tried already?**
I have tried re-running these tests locally and have been unable to reproduce this failure. This may be caused by resource constraints.

**Additional Context**
It looks like the logs on all three of these test failures show something similar:

<details>
  <summary>Click to expand!</summary>
  
```
DumpOutput(stdout):2022-04-07T06:08:55,582 [zookeeper.ServiceLock] DEBUG: event null None Expired
DumpOutput(stdout):2022-04-07T06:08:55,587 [tserver.TabletServer] ERROR: Lost tablet server lock (reason = SESSION_EXPIRED), exiting.
DumpOutput(stdout):2022-04-07T06:08:55,589 [server.GarbageCollectionLogger] DEBUG: gc G1 Young Generation=0.03(+0.00) secs G1 Old Generation=0.04(+0.00) secs freemem=71,002,128(-43,173,408) totalmem=142,606,336
```

</details>

<details>
  <summary>Click to expand!</summary>
  
```
DumpOutput(stdout):2022-04-06T06:19:08,847 [util.Retry] DEBUG: Sleeping for 1550ms before retrying operation
DumpOutput(stdout):2022-04-06T06:19:08,847 [util.Retry] DEBUG: Sleeping for 1529ms before retrying operation
DumpOutput(stdout):2022-04-06T06:19:10,334 [zookeeper.ZooSession] DEBUG: Session expired, state of current session : Expired
DumpOutput(stdout):2022-04-06T06:19:10,335 [zookeeper.DistributedWorkQueue] INFO : Got unexpected zookeeper event: None for /accumulo/2b5b3353-1305-4890-973c-2ec7b7e1de69/recovery
DumpOutput(stdout):2022-04-06T06:19:10,335 [zookeeper.ServiceLock] DEBUG: event null None Expired
DumpOutput(stdout):2022-04-06T06:19:10,345 [tserver.TabletServer] ERROR: Lost tablet server lock (reason = SESSION_EXPIRED), exiting.
DumpOutput(stdout):2022-04-06T06:19:10,347 [zookeeper.ZooSession] DEBUG: Removing closed ZooKeeper session to localhost:38779
DumpOutput(stdout):2022-04-06T06:19:10,347 [zookeeper.ZooSession] DEBUG: Connecting to localhost:38779 with timeout 15000 with auth
DumpOutput(stdout):2022-04-06T06:19:10,347 [server.GarbageCollectionLogger] DEBUG: gc G1 Young Generation=0.04(+0.00) secs G1 Old Generation=0.05(+0.00) secs freemem=66,295,976(-48,341,288) totalmem=142,606,336
DumpOutput(stdout):2022-04-06T06:19:10,347 [server.GarbageCollectionLogger] WARN : GC pause checker not called in a timely fashion. Expected every 15.0 seconds but was 18.5 seconds since last check
```

</details>

<details>
  <summary>Click to expand!</summary>
  
```
2022-02-05 00:18:42,997 [util.Retry] DEBUG: Sleeping for 1000ms before retrying operation
2022-02-05 00:18:42,995 [zookeeper.ZooSession] DEBUG: Connecting to localhost:44669 with timeout 15000 with auth
2022-02-05 00:18:43,396 [zookeeper.ZooSession] DEBUG: Removing closed ZooKeeper session to localhost:44669
2022-02-05 00:18:43,396 [zookeeper.ZooSession] DEBUG: Connecting to localhost:44669 with timeout 15000 with auth
2022-02-05 00:18:44,605 [zookeeper.DistributedWorkQueue] INFO : Got unexpected zookeeper event: None for /accumulo/1cd2ca23-e434-4e07-8e80-3c3ff5f53ee2/replication/workqueue
2022-02-05 00:18:44,605 [Audit] INFO : operation: permitted; user: root; client: 67.195.81.162:34616; action: authenticate;
2022-02-05 00:18:44,605 [zookeeper.DistributedWorkQueue] INFO : Got unexpected zookeeper event: None for /accumulo/1cd2ca23-e434-4e07-8e80-3c3ff5f53ee2/recovery
2022-02-05 00:18:44,605 [zookeeper.ZooLock] DEBUG: event null None Disconnected
2022-02-05 00:18:44,608 [Audit] INFO : operation: permitted; user: root; client: 67.195.81.162:34616; action: performSystemAction; principal: root;
2022-02-05 00:18:44,610 [tracer.ZooTraceClient] DEBUG: Processing event for trace server zk watch
2022-02-05 00:18:44,613 [zookeeper.DistributedWorkQueue] INFO : Got unexpected zookeeper event: None for /accumulo/1cd2ca23-e434-4e07-8e80-3c3ff5f53ee2/bulk_failed_copyq
2022-02-05 00:18:44,615 [zookeeper.DistributedWorkQueue] INFO : Got unexpected zookeeper event: None for /accumulo/1cd2ca23-e434-4e07-8e80-3c3ff5f53ee2/replication/workqueue
2022-02-05 00:18:44,615 [zookeeper.DistributedWorkQueue] INFO : Got unexpected zookeeper event: None for /accumulo/1cd2ca23-e434-4e07-8e80-3c3ff5f53ee2/recovery
2022-02-05 00:18:44,615 [zookeeper.ZooLock] DEBUG: event null None Expired
2022-02-05 00:18:44,618 [tserver.TabletServer] ERROR: Lost tablet server lock (reason = SESSION_EXPIRED), exiting.
2022-02-05 00:18:44,620 [server.GarbageCollectionLogger] DEBUG: gc G1 Young Generation=0.04(+0.00) secs G1 Old Generation=0.03(+0.00) secs freemem=175,325,160(-10,182,592) totalmem=209,715,200
2022-02-05 00:18:44,964 [datanode.DataNode] ERROR: 127.0.0.1:43529:DataXceiver error processing WRITE_BLOCK operation  src: /127.0.0.1:38814 dst: /127.0.0.1:43529
java.io.IOException: Premature EOF from inputStream
	at org.apache.hadoop.io.IOUtils.readFully(IOUtils.java:194)
	at org.apache.hadoop.hdfs.protocol.datatransfer.PacketReceiver.doReadFully(PacketReceiver.java:213)
	at org.apache.hadoop.hdfs.protocol.datatransfer.PacketReceiver.doRead(PacketReceiver.java:134)
	at org.apache.hadoop.hdfs.protocol.datatransfer.PacketReceiver.receiveNextPacket(PacketReceiver.java:109)
	at org.apache.hadoop.hdfs.server.datanode.BlockReceiver.receivePacket(BlockReceiver.java:496)
	at org.apache.hadoop.hdfs.server.datanode.BlockReceiver.receiveBlock(BlockReceiver.java:891)
	at org.apache.hadoop.hdfs.server.datanode.DataXceiver.writeBlock(DataXceiver.java:758)
	at org.apache.hadoop.hdfs.protocol.datatransfer.Receiver.opWriteBlock(Receiver.java:137)
	at org.apache.hadoop.hdfs.protocol.datatransfer.Receiver.processOp(Receiver.java:74)
	at org.apache.hadoop.hdfs.server.datanode.DataXceiver.run(DataXceiver.java:239)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-02-05 00:18:44,964 [datanode.DataNode] ERROR: 127.0.0.1:43529:DataXceiver error processing WRITE_BLOCK operation  src: /127.0.0.1:38818 dst: /127.0.0.1:43529
java.io.IOException: Premature EOF from inputStream
	at org.apache.hadoop.io.IOUtils.readFully(IOUtils.java:194)
	at org.apache.hadoop.hdfs.protocol.datatransfer.PacketReceiver.doReadFully(PacketReceiver.java:213)
	at org.apache.hadoop.hdfs.protocol.datatransfer.PacketReceiver.doRead(PacketReceiver.java:134)
	at org.apache.hadoop.hdfs.protocol.datatransfer.PacketReceiver.receiveNextPacket(PacketReceiver.java:109)
	at org.apache.hadoop.hdfs.server.datanode.BlockReceiver.receivePacket(BlockReceiver.java:496)
	at org.apache.hadoop.hdfs.server.datanode.BlockReceiver.receiveBlock(BlockReceiver.java:891)
	at org.apache.hadoop.hdfs.server.datanode.DataXceiver.writeBlock(DataXceiver.java:758)
	at org.apache.hadoop.hdfs.protocol.datatransfer.Receiver.opWriteBlock(Receiver.java:137)
	at org.apache.hadoop.hdfs.protocol.datatransfer.Receiver.processOp(Receiver.java:74)
	at org.apache.hadoop.hdfs.server.datanode.DataXceiver.run(DataXceiver.java:239)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

</details>

**Comment by dlmarion** [comment] 2022-05-12 19:05
Looking at the last two failures of this test, they both failed because of a ConnectionLoss to ZK.

**Comment by ctubbsii** [comment] 2022-11-16 08:06
I have not seen this in quite some time. None of the recent CI failures were caused by this. I think we can close this. We can reopen if it starts occurring again.

**Closed by ctubbsii** 2022-11-16 08:06 UTC
Labels: bug, test
