### ISSUE TITLE
Vfs2 error in Shell

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#439] opened 2018-04-24 23:00 UTC
I changed table.file.compress.type on a table and after writing to it so the vfs2 exception in the shell:

<pre>
06:37:55 {master} ~/sw/uno$ accumulo org.apache.accumulo.test.TestIngest -i uno -u root -p secret --rows 3000
2018-04-24 18:38:08,541 [trace.DistributedTrace] INFO : SpanReceiver org.apache.accumulo.tracer.ZooTraceClient was loaded successfully.
       3,000 records written |   10,489 records/sec |    3,087,000 bytes written | 10,793,706 bytes/sec |  0.286 secs   
Exception in thread "Thread-2" java.lang.RuntimeException: No files-cache implementation set.
	at org.apache.commons.vfs2.provider.AbstractFileSystem.getCache(AbstractFileSystem.java:209)
	at org.apache.commons.vfs2.provider.AbstractFileSystem.getFileFromCache(AbstractFileSystem.java:222)
	at org.apache.commons.vfs2.provider.AbstractFileSystem.resolveFile(AbstractFileSystem.java:332)
	at org.apache.commons.vfs2.provider.AbstractFileSystem.resolveFile(AbstractFileSystem.java:317)
	at org.apache.commons.vfs2.provider.AbstractFileObject.resolveFile(AbstractFileObject.java:2007)
	at org.apache.commons.vfs2.provider.AbstractFileObject.resolveFiles(AbstractFileObject.java:2052)
	at org.apache.commons.vfs2.provider.AbstractFileObject.getChildren(AbstractFileObject.java:1222)
	at org.apache.commons.vfs2.impl.DefaultFileMonitor$FileMonitorAgent.checkForNewChildren(DefaultFileMonitor.java:553)
	at org.apache.commons.vfs2.impl.DefaultFileMonitor$FileMonitorAgent.check(DefaultFileMonitor.java:667)
	at org.apache.commons.vfs2.impl.DefaultFileMonitor$FileMonitorAgent.access$200(DefaultFileMonitor.java:423)
	at org.apache.commons.vfs2.impl.DefaultFileMonitor.run(DefaultFileMonitor.java:376)
	at java.lang.Thread.run(Thread.java:748)

06:40:10 {master} ~/sw/uno$ accumulo shell -u root -p secret -e 'flush -t test_ingest'
2018-04-24 18:40:22,106 [trace.DistributedTrace] INFO : SpanReceiver org.apache.accumulo.tracer.ZooTraceClient was loaded successfully.
2018-04-24 18:40:22,387 [shell.Shell] INFO : Flush of table test_ingest initiated...
Exception in thread "Thread-2" java.lang.RuntimeException: No files-cache implementation set.
	at org.apache.commons.vfs2.provider.AbstractFileSystem.getCache(AbstractFileSystem.java:209)
	at org.apache.commons.vfs2.provider.AbstractFileSystem.getFileFromCache(AbstractFileSystem.java:222)
	at org.apache.commons.vfs2.provider.AbstractFileSystem.resolveFile(AbstractFileSystem.java:332)
	at org.apache.commons.vfs2.provider.AbstractFileSystem.resolveFile(AbstractFileSystem.java:317)
	at org.apache.commons.vfs2.provider.AbstractFileObject.resolveFile(AbstractFileObject.java:2007)
	at org.apache.commons.vfs2.provider.AbstractFileObject.resolveFiles(AbstractFileObject.java:2052)
	at org.apache.commons.vfs2.provider.AbstractFileObject.getChildren(AbstractFileObject.java:1222)
	at org.apache.commons.vfs2.impl.DefaultFileMonitor$FileMonitorAgent.checkForNewChildren(DefaultFileMonitor.java:553)
	at org.apache.commons.vfs2.impl.DefaultFileMonitor$FileMonitorAgent.check(DefaultFileMonitor.java:667)
	at org.apache.commons.vfs2.impl.DefaultFileMonitor$FileMonitorAgent.access$200(DefaultFileMonitor.java:423)
	at org.apache.commons.vfs2.impl.DefaultFileMonitor.run(DefaultFileMonitor.java:376)
	at java.lang.Thread.run(Thread.java:748)
</pre>

The data was written and flushed.  Nothing in the tserver logs.  Could be a configuration error but I was using Accumulo 1.8.1 and Hadoop 2.9.0.

**Comment by milleruntime** [comment] 2018-04-25 16:58
Unable to reproduce this error.

**Comment by jzgithub1** [comment] 2019-03-18 21:13
This may be solved with pull request 1034.

https://github.com/apache/accumulo/pull/1034

**Comment by ctubbsii** [comment] 2019-03-18 22:27
Duplicate of #933

**Closed by ctubbsii** 2019-03-18 22:27 UTC
Labels: duplicate
