### ISSUE TITLE
Azure Configuration property xxx.dfs.core.windows.net not found

### ISSUE THREAD

**Issue by Viv1986** [apache/accumulo#1850] opened 2020-12-28 16:19 UTC
**Describe the bug**
Hello,
Tryint to set azure datalake storage for accumulo 2.0 and
found your article at accumulo website
https://accumulo.apache.org/blog/2019/10/15/accumulo-adlsgen2-notes.html

hdfs work fine, but accumulo and have problem on start

<details>
<summary>Stack Trace (click to expand)</summary>

```java
2020-12-28 16:25:21,838 [start.Main] ERROR: Thread 'org.apache.accumulo.master.state.SetGoalState' died.
java.lang.IllegalStateException: Configuration property xxx.dfs.core.windows.net not found.
        at org.apache.accumulo.server.ServerInfo.<init>(ServerInfo.java:93)
        at org.apache.accumulo.server.ServerContext.<init>(ServerContext.java:59)
        at org.apache.accumulo.master.state.SetGoalState.main(SetGoalState.java:41)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.accumulo.start.Main.lambda$execMainClass$1(Main.java:166)
        at java.lang.Thread.run(Thread.java:745)
Caused by: Configuration property xxx.dfs.core.windows.net not found.
        at org.apache.hadoop.fs.azurebfs.AbfsConfiguration.getStorageAccountKey(AbfsConfiguration.java:356)
        at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystemStore.initializeClient(AzureBlobFileSystemStore.java:826)
        at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystemStore.<init>(AzureBlobFileSystemStore.java:151)
        at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystem.initialize(AzureBlobFileSystem.java:105)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3303)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:124)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3352)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3320)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:479)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:361)
        at org.apache.accumulo.core.volume.VolumeImpl.<init>(VolumeImpl.java:45)
        at org.apache.accumulo.core.volume.VolumeConfiguration.create(VolumeConfiguration.java:152)
        at org.apache.accumulo.server.fs.VolumeManagerImpl.get(VolumeManagerImpl.java:355)
        at org.apache.accumulo.server.ServerInfo.<init>(ServerInfo.java:91)
```
</details>

when I set  at `accumulo.properties`
```conf
instance.volumes=hdfs://first.xxxxx.cloudapp.net:8020/apps/accumulo/data,abfss://accumulo2@xxx.dfs.core.windows.net/
```

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Accumulo 2.0
 - Any Linux

**To Reproduce**
Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):
1. Setup Accumulo 2.0
2. Setup settings by https://accumulo.apache.org/blog/2019/10/15/accumulo-adlsgen2-notes.html
3. `accumulo init --add-volumes`

**Expected behavior**
Work with Azure

**Comment by ctubbsii** [comment] 2020-12-28 16:32
@karthick-rn or @arvindshmicrosoft Any ideas?

**Comment by karthick-rn** [comment] 2020-12-28 17:25
@Viv1986, Based on the description, looks like you added both HDFS & ABFS volumes at one go and ran `accumulo init --add-volumes`. In Accumulo 2.0, this need to be done in 2 steps as described in the blog.
1. Add HDFS volume in `accumulo.properties` file
`instance.volumes=hdfs://first.xxxxx.cloudapp.net:8020/apps/accumulo/data`
2. Run `accumulo init` to initialise Accumulo on HDFS
3. Now add ABFS volume as shown below 
`instance.volumes=hdfs://first.xxxxx.cloudapp.net:8020/apps/accumulo/data,abfss://accumulo2@xxx.dfs.core.windows.net/`
(make sure you add a directory in the ABFS URI for initialising)
4. Run `accumulo init --add-volumes` to initialise Accumulo on ABFS 
5. Start Accumulo services

Try this and let me know?

**Comment by Viv1986** [comment] 2020-12-28 17:33
@karthick-rn 
if you read my message, all this was already done

**Comment by karthick-rn** [comment] 2020-12-28 17:49
What version of Hadoop are you using?

**Comment by Viv1986** [comment] 2020-12-28 17:56
3.1
hadoop fs -ls abfs://accumulo2@xxx.dfs.core.windows.net/
Found 1 items
drwxr-xr-x   - accumulo accumulo  0 2020-12-25 10:56 abfs://accumulo2@xxx.dfs.core.windows.net/accumulo

**Comment by karthick-rn** [comment] 2020-12-29 13:47
Support for ABFS connector in the `hadoop-azure` module has been added from Hadoop 3.2.0 onwards (Refer [RN-3.2.0](https://hadoop.apache.org/docs/r3.2.0/hadoop-project-dist/hadoop-common/release/3.2.0/RELEASENOTES.3.2.0.html)). I'd suggest you upgrade Hadoop to 3.2.0 or above and let us know if you still see this issue.

**Comment by arvindshmicrosoft** [comment] 2020-12-29 18:43
@Viv1986 I think Karthick's suggestion to leverage Hadoop 3.2.x is a good one, given almost all of our testing with this configuration was done with Hadoop 3.2.1+

That said, given you seem to be able to access the ADLS Gen2 account through Hadoop commands, but Accumulo cannot see it, in my experience this is an indication of something missing in the classpath specified for Accumulo. Hadoop looks for the hdfs-site.xml and core-site.xml files (which is where the necessary security key information for accessing ADLS Gen 2 is located), within the classpath specified for the current binary.

As another option, if this is a dev/test cluster, it may be easier if you use the [Muchos](https://github.com/apache/fluo-muchos) project to set up the cluster on Azure. There is out-of-the-box support in Muchos, for using ADLS Gen 2 with Accumulo. Muchos also [correctly populates](https://github.com/apache/fluo-muchos/blob/b21c3da46b99c7ed8d28fc24b232f7908a264eb5/ansible/roles/accumulo/templates/accumulo-env.sh#L51-L62) the Accumulo classpath with the required paths. Further, when using Muchos, the ADLS Gen 2 account is accessed using Azure Managed Identities, which leverage OAuth, and avoid hard-coded storage account key based access.

You may also use a cluster setup using Muchos to compare and check for differences in classpaths between your custom setup above and the "reference" setup done through Muchos.

**Comment by karthick-rn** [comment] 2021-01-05 13:20
@Viv1986 Do you need any further help on this?

**Comment by karthick-rn** [comment] 2021-01-05 19:50
> @karthick-rn maybe you know how update hadoop from 3.1 to 3.2?

You can refer this upgrade [doc](https://hadoop.apache.org/docs/r3.2.1/hadoop-project-dist/hadoop-hdfs/HdfsRollingUpgrade.html) from Apache. If this is a dev/test environment and the data is reproducible, I would straightaway go with a fresh install of Hadoop 3.2.0 or above and not bother with the upgrade. Like @arvindshmicrosoft pointed above, you can leverage [Muchos](https://github.com/apache/fluo-muchos) for this purpose and configuring ADLS Gen2 will be taken care as part of the setup.

**Comment by ctubbsii** [comment] 2021-01-06 21:59
Closing this, since the user is being assisted with using Muchos to set up ADLS Gen2 on apache/fluo-muchos#383

**Closed by ctubbsii** 2021-01-06 21:59 UTC
Labels: bug
