### ISSUE TITLE
The context classloader did not work for a compaction strategy with 2.0.0-alpha-2

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#928] opened 2019-02-01 00:39 UTC
I attempted to test a custom compaction strategy with the 2.0.0-alpha-2 and tried loading it using the context classloader.  It could not find the class.

```
java.lang.ClassNotFoundException: test.KTCompactionStrat
	at org.apache.commons.vfs2.impl.VFSClassLoader.findClass(VFSClassLoader.java:178)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.accumulo.start.classloader.vfs.ContextManager.loadClass(ContextManager.java:185)
	at org.apache.accumulo.core.conf.ConfigurationTypeHelper.getClassInstance(ConfigurationTypeHelper.java:204)
	at org.apache.accumulo.core.conf.ConfigurationTypeHelper.getClassInstance(ConfigurationTypeHelper.java:174)
	at org.apache.accumulo.core.conf.Property.createTableInstanceFromPropertyName(Property.java:1266)
	at org.apache.accumulo.tserver.TabletServerResourceManager$TabletResourceManager.needsMajorCompaction(TabletServerResourceManager.java:844)
	at org.apache.accumulo.tserver.tablet.Tablet.needsMajorCompaction(Tablet.java:1572)
	at org.apache.accumulo.tserver.tablet.Tablet.initiateMajorCompaction(Tablet.java:1546)
	at org.apache.accumulo.tserver.tablet.MinorCompactionTask.run(MinorCompactionTask.java:103)
	at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:35)
	at org.apache.htrace.wrappers.TraceRunnable.run(TraceRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:35)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by keith-turner** [comment] 2019-02-01 16:06
Saw this in tserver err file, not sure if its related.

```
Exception in thread "Thread-3" java.lang.RuntimeException: No files-cache implementation set.
	at org.apache.commons.vfs2.provider.AbstractFileSystem.getCache(AbstractFileSystem.java:209)
	at org.apache.commons.vfs2.provider.AbstractFileSystem.getFileFromCache(AbstractFileSystem.java:222)
	at org.apache.commons.vfs2.provider.AbstractFileSystem.resolveFile(AbstractFileSystem.java:332)
	at org.apache.commons.vfs2.provider.AbstractFileSystem.resolveFile(AbstractFileSystem.java:317)
	at org.apache.commons.vfs2.provider.AbstractFileObject.resolveFile(AbstractFileObject.java:2007)
	at org.apache.commons.vfs2.provider.AbstractFileObject.resolveFiles(AbstractFileObject.java:2052)
	at org.apache.commons.vfs2.provider.AbstractFileObject.getChildren(AbstractFileObject.java:1222)
	at org.apache.commons.vfs2.impl.DefaultFileMonitor$FileMonitorAgent.checkForNewChildren(DefaultFileMonitor.java:553)
	at org.apache.commons.vfs2.impl.DefaultFileMonitor$FileMonitorAgent.check(DefaultFileMonitor.java:667)
	at org.apache.commons.vfs2.impl.DefaultFileMonitor$FileMonitorAgent.access$200(DefaultFileMonitor.java:423)
	at org.apache.commons.vfs2.impl.DefaultFileMonitor.run(DefaultFileMonitor.java:376)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ctubbsii** [comment] 2019-03-18 22:25
Closing as duplicate of #933 (since there's more comments on that thread).

**Closed by ctubbsii** 2019-03-18 22:25 UTC
Labels: blocker, v2.0.0
