### ISSUE TITLE
Garbage collector page on monitor weirdness

### ISSUE THREAD

**Issue by ivakegg** [apache/accumulo#3374] opened 2023-05-04 18:05 UTC
The garbage collector page dow not seem to be updating despite the logs showing that the collector is obviously running.  Also the Duration for the current GC shows as being -54y-135d which I believe is epoch.

Accumulo 2.1.1-SNAPSHOT (55d972a4)
CentOS 7.3

**Comment by ctubbsii** [comment] 2023-05-05 09:08
What version? If snapshot, please provide the closest git hash to what you're using.

**Comment by DomGarguilo** [comment] 2023-05-08 19:43
Also was `SimpleGarbageCollector` being run or something else?

**Comment by ctubbsii** [comment] 2023-05-10 02:33
> Also was `SimpleGarbageCollector` being run or something else?

I don't think our implementation is pluggable. The name is historical, because we changed the implementation internally a long time ago. So, I would assume it's this one.

**Comment by ivakegg** [comment] 2023-05-10 14:49
> What version? If snapshot, please provide the closest git hash to what you're using.

@ctubbsii It appears that the last external commit we have is 55d972a4

**Comment by ctubbsii** [comment] 2023-05-10 14:58
> > What version? If snapshot, please provide the closest git hash to what you're using.
> 
> @ctubbsii It appears that the last external commit we have is [55d972a](https://github.com/apache/accumulo/commit/55d972a4c750c81aba8c59f5841d6369ad40d519)

That is old, but I don't see any updates since then that would have fixed something like this. Is this reproducible?

**Comment by ivakegg** [comment] 2023-05-10 15:04
> > > What version? If snapshot, please provide the closest git hash to what you're using.
> > 
> > 
> > @ctubbsii It appears that the last external commit we have is [55d972a](https://github.com/apache/accumulo/commit/55d972a4c750c81aba8c59f5841d6369ad40d519)
> 
> That is old, but I don't see any updates since then that would have fixed something like this. Is this reproducible?

Yes it is

**Comment by AlbertWhitlock** [comment] 2023-05-15 14:14
@ivakegg .... on my instance I also saw the -54y-148d entry. After investigating I found it is because when gc of WAL was kicked off my instance couldn't find all of my volumes. I reconnected to 'new' volume and next gc found the volume and that allowed the value on monitor page to be updated. Perhaps a better 'default' value could be used other than epoch.

**Comment by ctubbsii** [comment] 2023-05-15 17:20
@AlbertWhitlock wrote:
> @ivakegg .... on my instance I also saw the -54y-148d entry. After investigating I found it is because when gc of WAL was kicked off my instance couldn't find all of my volumes. I reconnected to 'new' volume and next gc found the volume and that allowed the value on monitor page to be updated. Perhaps a better 'default' value could be used other than epoch.

What do you mean it couldn't find all your volumes? What did you see that indicated that was related to this?
What do you mean you "reconnected to 'new' volume"?

@ivakegg When you say that it doesn't appear to be updating, does it update when you refresh the page? Or not at all?

**Comment by ctubbsii** [comment] 2023-05-15 17:25
If somebody can reproduce this, it would be helpful to know what the contents of `/rest/gc` show when this is happening. It'd be helpful to know if the edge case is happening in the REST endpoint or in the web view.

**Comment by AlbertWhitlock** [comment] 2023-05-16 15:51
@ctubbsii   What do you mean it couldn't find all your volumes? What did you see that indicated that was related to this?

I have 2 instances defined in instance.volumes. When GC was executing it performed cleanup on root table, metadata table, and user table fine. When cleanup of WAL attempted it would try to find the second instance (actual physical machine) and I accidentally had them unconnected so it was throwing a java.net.NoRouteToHostException. Once I reconnected the machines, the GC runs fine.

**Comment by ctubbsii** [comment] 2023-05-16 16:09
> ... so it was throwing a java.net.NoRouteToHostException ...

So, you saw this in the GC's logs, then? And the malformed date on the monitor was only occurring when this exception was seen?

**Comment by AlbertWhitlock** [comment] 2023-05-16 17:54
@ctubbsii  So, you saw this in the GC's logs, then? And the malformed date on the monitor was only occurring when this exception was seen?
Correct on both. I saw the exception in the logs and correct, it was only happening when exception was occurring.

**Comment by ctubbsii** [comment] 2023-05-16 18:24
@AlbertWhitlock If you can reliably reproduce the error, can you check to see if it is fixed with #3403 ?

**Comment by keith-ratcliffe** [comment] 2023-05-17 18:44
> It'd be helpful to know if the edge case is happening in the REST endpoint or in the web view.

As far as the Duration value for the Current GC, I'm able to confirm that the web view and the rest endpoint agree, i.e., they're reflective of the same negative value, formatted differently of course

> When you say that it doesn't appear to be updating, does it update when you refresh the page? Or not at all?

I am unable to replicate this atm. With auto-refresh enabled, activity updates seem to be appearing with the expected frequency for all the GC types, just that the Duration for Current GC is always the -54y-1XXd value

I'll see if I can get our system patched with your updates from #3403 and then report back

**Comment by ctubbsii** [comment] 2023-05-17 22:53
Should be fixed with my latest commit in #3403

**Closed** 2023-05-18 14:26 UTC
Labels: bug
