### ISSUE TITLE
WAL recovery enhancements and tooling

### ISSUE THREAD

**Issue by adamjshook** [apache/accumulo#535] opened 2018-06-20 17:34 UTC
The changes in #458 introduced a number of state checks that we are experiencing.  As far as I know there isn't any tooling around troubleshooting corrupt WAL files that are unrecoverable by Accumulo (please correct me if I am wrong!) and replacing the WAL with an empty one isn't a good option.

I'd like to know a little more about the various `IllegalStateExceptions` themselves and what kind of WAL surgery could be done.  Either creating a new tool to manually assist with recovery of the mutations or enhancements to the process itself so Accumulo can make the choices for us.

**Comment by adamjshook** [comment] 2018-06-20 17:39
I'm happy to do the leg work on this, but could someone help clue me in on how/why the WAL would be considered in an illegal state, and what could be done to remove/fix the illegal state?  The ones I am specifically experiencing are the `Saw consecutive COMPACTION_FINISH events` and `COMPACTION_FINISH (without preceding COMPACTION_START) is not followed by a successful minor compaction`.  Are exceptions the way to go with these or would logging be a better option since replaying the mutations is important? (I'm unfamiliar with the details of WAL recovery but am going over the code now).

**Comment by ctubbsii** [comment] 2018-06-20 19:38
I spoke to @keith-turner at length about this, and we (mostly Keith) came to the conclusion that these two errors *might* occur if you stop writing to one tablet, but continue writing mutations to another, and the logs roll over. In both cases, these exceptions could be thrown as a false positive, when there is no data to recover for that tablet, because the WAL containing the `COMPACTION_START` event could have been garbage collected.

Worse, this scenario may not be tested for, because our continuous ingest tests don't ever stop writing to a tablet.

The workaround would be to inspect the WALs and verify that there is no data for the tablet which produced the exception during recovery, and remove the entries in the affected tablet, and to repeat for each affected tablet. This is not ideal, but if somebody can verify that this is what is happening (it's still just speculation right now), we could proceed with a fix for 1.9.2. The good news is that there shouldn't be any data loss, if this is what is happening. It's just an error when there's no data necessary to recover.

Some possible fixes we discussed, if the issue can be verified:

1. Check that there are no data events in the WALs for that tablet, before throwing the exception.
2. Don't mark a WAL inactive prematurely, even if it has only a `COMPACTION_START` event with no data.

More investigation is needed to verify the problem, and possible fixes, though.

**Comment by adamjshook** [comment] 2018-06-20 19:51
Thanks, @ctubbsii.  I'm about to start working on a tool to run through the recovery process outside of Accumulo to help me step through the affected log and get a clearer picture on what is happening during recovery.

**Comment by ctubbsii** [comment] 2018-06-20 19:54
Also, the error messages are confusing. Both of the error messages you pasted here are reporting something similar: a missing `COMPACTION_START` event. In the "consecutive" case, it's fine that the first `COMPACTION_FINISH` is without a corresponding `START`, so long as the the one that follows has a `START` (and it doesn't, hence the error). In the second "not followed by a successful minor compaction" case, it is just pointing out that there's a single `FINISH` all alone with a missing `START`.

Both error messages could be improved.

**Comment by adamjshook** [comment] 2018-06-21 16:37
Working through fixing the tablets on our cluster -- Regarding recovery, each tablet recovers the relevant mutations from the WAL, yes?  Once tablet recovery has settled down, swapping out a WAL file would only affect the tablets with these errors.  So if there are no mutations for the given extent, then it'd be safe to swap it out with an empty and then there wouldn't be any data loss (no mutations for the busted tablet and all the other tablets have already recovered).

As an aside, it'd be good to add the broken WAL in the error message.

**Comment by ctubbsii** [comment] 2018-06-21 17:42
@adamjshook Yes, each tablet should recover its own relevant mutations from the sorted WAL logs, which are created from the individual WAL files.

If there are no mutations for the given extent / tablet, then swapping out with an empty should be fine. Were you able to verify that the affected tablets had no relevant mutations in the WAL?

**Comment by adamjshook** [comment] 2018-06-21 18:18
I'm trudging my way through them... There are 15 affected tablets and I've checked one so far and it doesn't have any mutations -- just a single `COMPACTION_FINISH` event.  Working my way through the tooling to make it a little easier to diagnose.

**Comment by keith-turner** [comment] 2018-06-21 19:13
> Within that loop there is only one COMPACTION_FINISH event, but if I remove the exception being thrown there are 80 mutations that need to be replayed.

@adamjshook  do you know how the sequence numbers of those mutations compare to the sequence number of the COMPACTION_FINISH event?

**Comment by adamjshook** [comment] 2018-06-21 19:32
For the one tablet that I have been working on, logging the error regarding `COMPACTION_FINISH` instead of throwing an exception. Four WALs total.

```
findLastStartToFinish
COMPACTION_FINISH tabletId: 390 seq: 1295
COMPACTION_FINISH (without preceding COMPACTION_START) is not followed by a successful minor compaction in log: 7721209c-727f-4cba-aadc-b9b8482224ac
playbackMutations numlogs: 4 tabletId: 390 recoverySeq: 0
MANY_MUTATIONS tabletId: 390 seq: 1295 size: 28
MANY_MUTATIONS tabletId: 390 seq: 1295 size: 26
MANY_MUTATIONS tabletId: 390 seq: 1295 size: 26
Finished recovery
KeyExtent 1;85766;8294 has 80 mutations
```

**Comment by adamjshook** [comment] 2018-06-21 20:32
Related question (cc @joshelser) -- would the original bugs from 1.8.0+ be prevalent in the replication system?  From what I can tell they are strictly related to recovery and the replication system reads through the WAL serially looking for `MUTATION` and `MANY_MUTATIONS` events.

**Comment by joshelser** [comment] 2018-06-21 20:35
> From what I can tell they are strictly related to recovery and the replication system reads through the WAL serially looking for MUTATION and MANY_MUTATIONS events.

You're right here. I haven't done enough digging into the core-problem that was fixed, but I'd be surprised if it's an issue.

**Comment by adamjshook** [comment] 2018-06-26 18:21
@keith-turner @ctubbsii Do you think it’d be safe for me to apply a patch on our end to temporarily remove the IllegalStateExceptions and roll with that? Or would we be better off waiting for some official patches? Thanks!

**Comment by ctubbsii** [comment] 2018-06-26 21:01
I would be hesitant to call anything "safe" until we've finished testing, but if you wanted to test, you could try  the patch in #541 and the related #540 (#539 may also fix another WAL bug).

**Comment by adamjshook** [comment] 2018-06-27 17:57
Thanks, I'll get this out on our dev/stage systems and help out on the testing.

**Comment by mikewalch** [comment] 2018-06-28 22:30
I added pausing to continuous ingest tests to reproduce this exception.  I ran 2 tests today using 1.9.1 and was able to reproduce this problem within an hour each time.  I am now running with Keith's patches to see if they fix this bug.  I will let everyone knows how this testing goes.

**Comment by mikewalch** [comment] 2018-06-29 15:41
Testing went well. I did not see the exception/table problem occur overnight.  However, I would like to test some more.

**Comment by keith-turner** [comment] 2018-07-10 13:40
@ctubbsii  are you ok removing the blocker label from this issue?

**Comment by ctubbsii** [comment] 2018-07-10 21:01
@keith-turner  Isn't it already fixed by the 3 WAL PRs you had? Can we just close it instead? The original issue was requesting tooling for an issue that was discovered, but through discussion, we realized that the issue was a bug. I would think this original request is now OBE, since the bugs should no longer occur. We could always revisit the idea of creating additional tooling to assist manual recovery in a subsequent issue, if it's really necessary.

**Comment by keith-turner** [comment] 2018-07-10 21:13
> Can we just close it instead?

I think tooling around reading WAL files would be useful. Kinda like `accumulo rfile-info` command.  However, that was probably not the specific purpose of this issue.  I am not sure  what to do this issue,  I would leave that to @adamjshook.   @ctubbsii the reason I asked you about removing the blocker label was because I saw you added it.

**Comment by keith-turner** [comment] 2018-07-10 21:16
> Isn't it already fixed by the 3 WAL PRs you had?

Yeap

**Comment by ctubbsii** [comment] 2018-07-10 21:19
I created #554 to separate out the tooling request from the bug tracking and specific issues which inspired the request. I'll close this.

**Closed by ctubbsii** 2018-07-10 21:19 UTC
Labels: blocker, bug, v1.9.2, v2.0.0
