### ISSUE TITLE
Tserver wait timeout is not forcing startup to continue

### ISSUE THREAD

**Issue by ddanielr** [apache/accumulo#3159] opened 2023-01-11 14:14 UTC
**Describe the bug**
If accumulo is started with the following properties, startup will exceed `5min` as `max.wait` never forces the startup process to continue. 
`master.startup.tserver.avail.min.count=<# of tservers>`
`master.startup.tserver.avail.max.wait=5min`

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 1.10.x, 2.1.x

**To Reproduce**
I used [Fluo-uno](https://github.com/apache/fluo-uno) to replicate this bug:
Note: The minimum number of tservers available should be set higher than your expected total tserver count.

***Accumulo 1.10.2***
1. Add the following properties to `conf/accumulo/1/accumulo-site.xml`
```
<property>
   <name>master.startup.tserver.avail.max.wait</name>
   <value>5m</value>
</property>
<property>
    <name>master.startup.tserver.avail.min.count</name>
    <value>3</value>
</property>
```
 2. Modify the `ACCUMULO_VERSION` in `conf/uno.conf` to match 1.10.2. 
`export ACCUMULO_VERSION=${ACCUMULO_VERSION:-1.10.2}`

3. Fetch & Start accumulo
`source <(./bin/uno env)`
`uno fetch accumulo`
`uno start accumulo`

4. View logs to see startup continuing to be blocked after 300 seconds 
`tail -f install/logs/accumulo/master_<hostname>.log`
```
2023-01-10 03:53:22,451 [master.Master] INFO : Blocking for tserver availability - need to reach 3 servers. Have 1 Time spent blocking 15 sec.
2023-01-10 03:53:52,501 [master.Master] INFO : Blocking for tserver availability - need to reach 3 servers. Have 1 Time spent blocking 45 sec.
2023-01-10 03:54:37,552 [master.Master] INFO : Blocking for tserver availability - need to reach 3 servers. Have 1 Time spent blocking 90 sec.
2023-01-10 03:55:37,602 [master.Master] INFO : Blocking for tserver availability - need to reach 3 servers. Have 1 Time spent blocking 150 sec.
2023-01-10 03:56:52,652 [master.Master] INFO : Blocking for tserver availability - need to reach 3 servers. Have 1 Time spent blocking 225 sec.
2023-01-10 03:58:22,703 [master.Master] INFO : Blocking for tserver availability - need to reach 3 servers. Have 1 Time spent blocking 315 sec.
2023-01-10 04:00:07,753 [master.Master] INFO : Blocking for tserver availability - need to reach 3 servers. Have 1 Time spent blocking 420 sec.
```

***Accumulo 2.1***
1. Add the following properties to `fluo-uno/conf/accumulo/2/accumulo.properties`
```
manager.startup.tserver.avail.min.count=3
manager.startup.tserver.avail.max.wait=5m
```
2. Fetch & start accumulo
`source <(./bin/uno env)`
`uno fetch accumulo`
`uno setup accumulo`

4. View logs to see startup continuing to be blocked after 300 seconds
`cat install/logs/accumulo/manager_<hostname>.log | grep Blocking`
```
2023-01-11T13:46:08,511 [manager.Manager] INFO : Blocking for tserver availability - need to reach 3 servers. Have 1 Time spent blocking 0 sec.
2023-01-11T13:46:23,562 [manager.Manager] INFO : Blocking for tserver availability - need to reach 3 servers. Have 1 Time spent blocking 15 sec.
2023-01-11T13:46:53,612 [manager.Manager] INFO : Blocking for tserver availability - need to reach 3 servers. Have 1 Time spent blocking 45 sec.
2023-01-11T13:47:38,662 [manager.Manager] INFO : Blocking for tserver availability - need to reach 3 servers. Have 1 Time spent blocking 90 sec.
2023-01-11T13:48:38,713 [manager.Manager] INFO : Blocking for tserver availability - need to reach 3 servers. Have 1 Time spent blocking 150 sec.
2023-01-11T13:49:53,763 [manager.Manager] INFO : Blocking for tserver availability - need to reach 3 servers. Have 1 Time spent blocking 225 sec.
2023-01-11T13:51:23,813 [manager.Manager] INFO : Blocking for tserver availability - need to reach 3 servers. Have 1 Time spent blocking 315 sec.
2023-01-11T13:53:08,864 [manager.Manager] INFO : Blocking for tserver availability - need to reach 3 servers. Have 1 Time spent blocking 420 sec.
```

**Expected behavior**
Given `manager.startup.tserver.avail.min.count` and `manager.startup.tserver.avail.max.wait` are set. 
When `tserver.avail.min.count` is not reached by the time specified in `tserver.avail.max.wait`,
Then the startup process continues on.

**Additional context**
This is related to issue #3157 but is only focused on the expected behavior of the `tserver.avail.max.wait` property.

**Comment by ddanielr** [comment] 2023-01-11 14:18
Focusing on 1.10.2, the problem seems to come from the Retry logic used. 
https://github.com/apache/accumulo/blob/1.10/server/master/src/main/java/org/apache/accumulo/master/Master.java#L1516 

If `tserverRetry` has retries available, then it will always return true.
`tserverRetry` was created with infinite retries, so this logic will always return true and the timeout is never reached.
https://github.com/apache/accumulo/blob/1.10/server/master/src/main/java/org/apache/accumulo/master/Master.java#L1507

**Comment by ddanielr** [comment] 2023-01-11 14:24
I wanted to play around with the Retry object, so I staged a fix that replaces the `infiniteRetries()` with `maxRetries()` and calculated the value based on the max number of attempts that could be completed in the set interval. 

https://github.com/ddanielr/accumulo/pull/5/files#diff-56945d7261689b2323a668699ab5865a1e48ec8424b0d612091d29ae0f2fc67cR1513

This technically works, but it's not an exact match to the expected timeout interval that is set in the property. 

So, should a retry object be used for this operation? Or would a simple timeout loop be better suited?

**Comment by EdColeman** [comment] 2023-01-11 15:15
Maybe a loop here would be better to handle multiple conditions.  I think that the loop would need to support:

- allow for infinite reties
- be able to ignore / disable # tservers barrier
- print progress, wait conditions periodically, independent of the wait time.

**Comment by cshannon** [comment] 2023-01-13 23:17
You mentioned the expected behavior is the start up process continues on if the max timeout is hit but I'm wondering what the correct behavior is. Obviously we don't want to spin in a loop forever but but I would think intuitively that if the min number of servers isn't reached by the timeout that would be a fatal error and we would should stop the process and not continue on but shutdown.

**Comment by ddanielr** [comment] 2023-01-14 00:58
@cshannon  The max timeout behavior you suggested makes sense, but I'm cautious about inversely changing the behavior of a property.

The is the current definition of the property behavior. 
https://github.com/apache/accumulo/blob/fbe1ee8cfc98f788329208419d682429c90784c2/core/src/main/java/org/apache/accumulo/core/conf/Property.java#L346-L349 

Would it make sense to have two sets of these properties? 
One for the critical path, the other as a churn/balancing safeguard for startup?

The timeout logic you are suggesting could be rolled into the new "critical" property and we wouldn't flip existing/expected property behavior. 

If not reached, startup will be terminated (timeout).
`manager.startup.tserver.critical.min.count`
`manager.startup.tserver.critical.timeout`

if not reached, startup will be delayed, not terminated (wait time).
`manager.startup.tserver.avail.min.count`
`master.startup.tserver.avail.max.wait=5min`

**Comment by Manno15** [comment] 2023-01-16 17:20
@cshannon It really depends on the goal of the property. I don't think the intended purpose is to fully block accumulo from starting up. Accumulo should be able to run even if some Tservers fail to start or take a prolonged time. Delaying start-up seems to be more intended to stop unnecessary balancing if some tservers start up quicker than others.

**Comment by EdColeman** [comment] 2023-01-17 14:32
Some of this conversation was covered in #3157.  The specific use case the initial change was to provide a guarantee that some number of tservers were up and available to handle tablet assignments on start-up.  Assume that you are using something like pssh and it is working through a list of servers to start the tservers - it does not get very far through the list before the manager starts flooding the first few tservers that have checked in with the entire cluster assignments - and then that takes a long while to rebalance.

The comments in this thread show the conflicting opinions on how this should be used:

- wait forever until n are available (current behavior).
- wait for t until n are available - fail if n is not reached if t is exceeded.
- wait for t until n are available - if t reached, go with what you have.

None of these are "incorrect" and depended on user expectations.

The core issue is that if the manager is started first, then almost all tablets are assigned to the first few tservers that register.  First root, then metadata, then everything else... So when the manager starts, as soon as it sees the first tserver register, the root and metadata table tablets get assigned there - then it starts assigning everything else - maybe a few tservers have come on line - but likely not nearly the number expected and not enough to handle the assignments quickly. 

If I set a small number, say 10% of total expected servers then my expectations on continuing are going to different than if I choose 99%.  With 10% I have set a bar that accepts that rebalancing may occur, but there are enough tservers to handle those assignments.  With 99% I am likely trying to minimize any rebalencing and even if I reach 98% after a reasonable amount of time then I accept proceeding.

The original intent was more towards the 10% case - guarantee that there is a minimum number of tservers present.

The issue raised in #3157 expected behavior more like the 99% case.

Another factor may be the ability to recover / reset.  If the timeout is infinite or fails and n is not reached, the assignments never start - you could change n in ZooKeeper, or change the property value and restart the master.  If the assignments ignore n and start after t - then you basically need to accept the situation and wait.

**Comment by dlmarion** [comment] 2023-01-17 14:38
`wait for t until n are available - fail if n is not reached if t is exceeded.`

This is incorrect based on the current wording of the properties.

**Comment by EdColeman** [comment] 2023-01-17 14:44
```wait for t until n are available - fail if n is not reached if t is exceeded.```

Is my interpretation of what @cshannon  was proposing in an earlier comment.

**Comment by dlmarion** [comment] 2023-01-17 14:48
ah, ok. We could add a new property to support that case.

**Comment by EdColeman** [comment] 2023-01-17 14:50
Any of the options are valid - we just need to decide which one meets most needs and then document that.  I lean towards the wait forever or fail because they allow recovery with minimal disruption.

**Comment by cshannon** [comment] 2023-01-18 00:13
I agree with @EdColeman that it's really up for interpretation as to what the property means and my comment was mostly pointing out that as someone who isn't too familiar with those properties it looked to me at first glance like it might make sense for the system to fail and halt if the minimum servers are not met in the time frame. But if that's not the intent then that is fine as long as things are well documented.

If the intent is to not stop and to continue then maybe we should add another property as @dlmarion  mentioned. I think the halting case is still valid (someone may want to shut down and not continue starting the cluster if the mininum number of servers doesn't come online as there could be a larger issue) so I think it is worthwhile to add but could be done as another Issue/PR of course.

**Comment by ddanielr** [comment] 2023-01-18 01:43
I agree with @cshannon that the halting behavior is a valid desire, just not for the original properties. 
A kubernetes deployment of accumulo would benefit from having the "critical.min.count" and "wait and fail" behavior properties available to use for defining startup and readiness probes.

@EdColeman I don't see this as making any decisions about cluster management since these properties are all optional. 
If we were to set them to required values then I could see that being a decision and carrying backlash. 

---

Based on the discussion so far, it sounds like fixing the original timeout logic to be  "Wait and Continue" is the correct move. 

Adding a second set of properties for "critical.min.count" and "wait and fail" behavior is a valid requirement and makes sense to add. However, that work should be completed in a separate ticket. 

If that sounds good, I'll work on this timeout fix and make the additional ticket for implementing the second optional property set.

**Comment by EdColeman** [comment] 2023-03-10 18:28
Closed with https://github.com/apache/accumulo/pull/3231

**Closed by EdColeman** 2023-03-10 18:28 UTC
Labels: bug
