### ISSUE TITLE
Broken or Flaky test: GarbageCollectorIT

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#3867] opened 2023-10-18 19:53 UTC
**Test name(s)**
 - org.apache.accumulo.test.functional.GarbageCollectorIT.testRootUniqueMutationDelete

**Describe the failure observed**

An assertion that there were no delete candidates prior to the test code running failed. The relevant test code and assertion:

```java
    // Ensure that no other candidates exist before starting test.
    Iterator<GcCandidate> cIter = ample.getGcCandidates(datalevel);

    ArrayList<GcCandidate> tempCandidates = new ArrayList<>();
    while (cIter.hasNext()) {
      GcCandidate cTemp = cIter.next();
      log.debug("PreExisting Candidate Found: {}", cTemp);
      tempCandidates.add(cTemp);
    }
    assertTrue(tempCandidates.size() == 0);
```

The failure was:
```
[INFO] Running org.apache.accumulo.test.functional.GarbageCollectorIT
[ERROR] Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 262.5 s <<< FAILURE! -- in org.apache.accumulo.test.functional.GarbageCollectorIT
[ERROR] org.apache.accumulo.test.functional.GarbageCollectorIT.testRootUniqueMutationDelete -- Time elapsed: 15.80 s <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:31)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:180)
	at org.apache.accumulo.test.functional.GarbageCollectorIT.testRootUniqueMutationDelete(GarbageCollectorIT.java:328)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.api.AssertTimeoutPreemptively.lambda$submitTask$3(AssertTimeoutPreemptively.java:95)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Testing Environment:**

 - Version of this project: 3.1.0-SNAPSHOT
 - First commit known to fail (or current commit): Unknown, happened on 85b7d3be9f7c8942fe2ecd2c4a97e335cb150c8b
 - Other environment details:
```
Apache Maven 3.9.0 (9b58d2bad23a66be161c4664ef21ce219c2c8584)
Maven home: /var/lib/jenkins/tools/hudson.tasks.Maven_MavenInstallation/Maven_3.9.0
Java version: 17.0.8, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-17-openjdk-17.0.8.0.7-1.fc38.x86_64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.5.6-200.fc38.x86_64", arch: "amd64", family: "unix"
```

**What have you tried already?**

The IT got re-run, and passed on a subsequent attempt.

**Additional context**

This code is similar in 2.1, so any failure here is probably applicable to 2.1 as well.
The `assertTrue(size == 0)` should also be changed to `assertEquals(0, size)`

**Comment by ddanielr** [comment] 2023-11-03 17:33
Merged #3917 to 2.1 and main branches. Since merging I haven't been able to reproduce the test failing.

**Closed** 2023-11-13 15:28 UTC
Labels: bug, test
