### ISSUE TITLE
Broken or Flaky test: MemoryStarvedScanIT

### ISSUE THREAD

**Issue by EdColeman** [apache/accumulo#3372] opened 2023-05-04 14:33 UTC
Accumulo version: 3.0.0-SNAPSHOT
Test: MemoryStarvedScanIT

The have been repeated failures of some of the MemoryStarvedScanIT in the Jenkins runs.

org.apache.accumulo.test.functional.MemoryStarvedScanIT.testBatchScanPauses (Line 386)
org.apache.accumulo.test.functional.MemoryStarvedScanIT.testBatchScanReturnsEarlyDueToLowMemory (Line 316)

Both failed looking for the LOW_MEM_DETECTED metric - this was recently added may be a race condition where it takes time for the metric to be updated.  It passes locally

A fix may be to check / wait to see if the metric is updated during a future metrics update cycle.

**Comment by ctubbsii** [comment] 2023-05-05 09:07
The error I've seen is:

```
[WARNING] org.apache.accumulo.test.functional.MemoryStarvedScanIT.testBatchScanPauses
[ERROR]   Run 1: MemoryStarvedScanIT.testBatchScanPauses:334 expected: <0> but was: <1>
[ERROR]   Run 2: MemoryStarvedScanIT.testBatchScanPauses:386 expected: <1> but was: <0>
[ERROR]   Run 3: MemoryStarvedScanIT.testBatchScanPauses:386 expected: <1> but was: <0>
[ERROR]   Run 4: MemoryStarvedScanIT.testBatchScanPauses:386 expected: <1> but was: <0>
[ERROR]   Run 5: MemoryStarvedScanIT.testBatchScanPauses:386 expected: <1> but was: <0>
[INFO]   Run 6: PASS
[INFO] 
[WARNING] org.apache.accumulo.test.functional.MemoryStarvedScanIT.testBatchScanReturnsEarlyDueToLowMemory
[ERROR]   Run 1: MemoryStarvedScanIT.testBatchScanReturnsEarlyDueToLowMemory:316 expected: <1> but was: <0>
[INFO]   Run 2: PASS
```

**Comment by Manno15** [comment] 2023-05-14 15:10
With some additional testing and logs, I confirmed the issue is the `LOW_MEM_DETECTED` value is reset back to 0 on the next metrics call after being set to 1. An additional check to now update the value after being set should alleviate the flakiness.

**Comment by ctubbsii** [comment] 2023-06-07 16:51
Assigned to @EdColeman because he told me he's already looking into it.

**Closed** 2023-06-23 20:28 UTC
Labels: blocker, bug, test
