### ISSUE TITLE
Thrift frame size errors

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#3042] opened 2022-10-25 16:07 UTC
**Describe the bug**
Seeing error messages like the following in the manager, gc, and compaction coordinator logs:
```
[rpc.CustomNonBlockingServer$CustomFrameBuffer] ERROR: Read a frame size of 369295362, which is bigger than the maximum allowable frame size 16384000 for ALL connections.
[rpc.CustomNonBlockingServer$CustomFrameBuffer] ERROR: Read an invalid frame size of -2143289088. Are you using TFramedTransport on the client side?
```

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 2.1.0-rc1

**Comment by DomGarguilo** [comment] 2022-10-25 16:10
I had been seeing this with some frequency as well:
![image](https://user-images.githubusercontent.com/47725857/197826191-599d7f78-5c3c-4f87-a06d-590bec04b5bb.png)

**Comment by ctubbsii** [comment] 2022-10-25 16:22
@dlmarion could this be caused by a bug in the multiplexed RPCs? Or possibly an outdated internal fork of Thrift client code we copied into our own project?

**Comment by dlmarion** [comment] 2022-10-25 16:23
unknown. looking...

**Comment by DomGarguilo** [comment] 2022-10-25 16:24
I was seeing this when I had external compaction enabled. Now, running a cluster with **internal** compactions, I am not seeing this.

**Comment by dlmarion** [comment] 2022-10-25 16:46
But I'm seeing this in the manager, gc, and compaction coordinator logs. I'm not sure why I would be seeing it in the gc logs if it was just related to external compactions

**Comment by dlmarion** [comment] 2022-10-25 16:49
> could this be caused by a bug in the multiplexed RPCs?

I don't think so, as the multiplexing is at the protocol level and the frame buffer is at the transport level. Still looking...

**Comment by DomGarguilo** [comment] 2022-10-25 17:03
> I was seeing this when I had external compaction enabled. Now, running a cluster with **internal** compactions, I am not seeing this.

Nevermind. I just got this again on the manager with internal compactions. Only once though, whereas I was getting it a lot before.

**Comment by dlmarion** [comment] 2022-10-25 17:12
I think for the GC process to get it, it has to come from the Monitor. From what I can tell the clients are using a TFramedTransport.

**Comment by dlmarion** [comment] 2022-10-25 19:03
So, I don't think this is a blocker. Everything with the test is still running - to include Accumulo processes, CI Ingest processes, and CI Agitator.

**Comment by ctubbsii** [comment] 2022-10-26 01:46
So, one thing that can cause this is network analysis software doing port scans/probes or anti-virus checking for stuff. Thrift might try to interpret some random bytes on the wire from that kind of stuff, and fail here when it doesn't work because it parsed out some integer that won't work. Be sure you're not running into any of that.

**Comment by ctubbsii** [comment] 2022-10-26 02:59
I will create a 2.1.0-RC2 without a fix for this, but I'm still tracking this for 2.1.0 because it may still end up blocking a release. If it doesn't, we can bump it off to 2.1.1 (assuming it's a problem, and not something scanning ports with pings or something like that)

**Comment by DomGarguilo** [comment] 2022-10-26 13:53
> So, one thing that can cause this is network analysis software doing port scans/probes or anti-virus checking for stuff. Thrift might try to interpret some random bytes on the wire from that kind of stuff, and fail here when it doesn't work because it parsed out some integer that won't work. Be sure you're not running into any of that.

I was seeing this on a generic Centos 7 image which I assume does not ship with those sort of tools. Might be something similar though, not sure. Just commenting in case this helps narrow things down.

**Comment by dlmarion** [comment] 2022-10-26 14:30
These messages come from the Thrift [FrameBuffer](https://github.com/apache/thrift/blob/master/lib/java/src/main/java/org/apache/thrift/server/AbstractNonblockingServer.java#L311) class. It's possible that we could print the client address to the log to try and identify the culprit.

**Comment by dlmarion** [comment] 2022-10-26 14:43
Put up a PR for additional logging against `main`. If we need to do RC3, then we can change the target branch and merge it in.

**Comment by ctubbsii** [comment] 2022-10-26 15:06
Go ahead and put the target branch for 2.1 anyway. That way, it will be included in 2.1.1 if there's no 2.1.0-rc3

**Comment by dlmarion** [comment] 2022-10-26 15:14
target branch changed

**Closed** 2022-10-26 17:29 UTC
Labels: bug

**Comment by dlmarion** [comment] 2022-10-31 13:37
I didn't see any of these errors while testing 2.1.0 RC4, so I think that maybe something external to Accumulo may have been trying to test open ports or something.
