### ISSUE TITLE
Add pre-emption to fate

### ISSUE THREAD

**Issue by Manno15** [apache/accumulo#2206] opened 2021-07-16 19:30 UTC
Original issue from Jira ticket: https://issues.apache.org/jira/browse/ACCUMULO-2633 and somewhat related to another Jira ticket: https://issues.apache.org/jira/browse/ACCUMULO-2119. 

Snippet from the ticket: 

```
It would be nice if FATE operations could be pre-empted. 
For example, if a compaction is running and a user issues a table delete, 
then the compaction does not need to be completed because that data will be dropped anyway.
```

The second ticket relates to canceling an ongoing compaction if a table delete is issued. That could be done in a separate issue but I included them together for now.

**Comment by ctubbsii** [comment] 2021-07-16 21:01
This, and the two referenced JIRA issues seem very similar to #2182 in their intended outcome. I don't think we have a strong need to change FaTE's architecture to support preemption more generically than that.

**Comment by Manno15** [comment] 2021-07-16 21:07
I did not see that issue so that is my mistake. I agree that the goals are similar so this issue can probably be closed along with those Jira tickers.

**Comment by Manno15** [comment] 2021-07-16 21:08
There is also Jira ticket [2535](https://issues.apache.org/jira/browse/ACCUMULO-2535) that falls under this umbrella as well.

**Comment by ctubbsii** [comment] 2021-07-16 21:15
> There is also Jira ticket [2535](https://issues.apache.org/jira/browse/ACCUMULO-2535) that falls under this umbrella as well.

Possibly. It seemed that the underlying cause had not been identified on that one. It may not have been compaction-related. Regardless, it should be closed as well, because it's either the same issue as here, or it's something we don't have enough information to reproduce.

**Closed** 2021-07-16 21:22 UTC
Labels: enhancement
