### ISSUE TITLE
SslIT is timing out

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2626] opened 2022-04-13 10:31 UTC
I ran this IT locally and saw it time out during the bulk test. It looks like there might be some concurrency problems with all the ITs that this IT is running.

**Comment by milleruntime** [comment] 2022-04-13 10:56
Exception being thrown in the Client:
<pre>
2022-04-13T06:37:33,846 [clientImpl.ScannerIterator] DEBUG: Exception when closing scan session
java.lang.IllegalStateException: This client was closed.
	at org.apache.accumulo.core.clientImpl.ClientContext.ensureOpen(ClientContext.java:147) ~[classes/:?]
	at org.apache.accumulo.core.clientImpl.ClientContext.getTransportPool(ClientContext.java:1018) ~[classes/:?]
	at org.apache.accumulo.core.rpc.ThriftUtil.getClient(ThriftUtil.java:129) ~[classes/:?]
	at org.apache.accumulo.core.rpc.ThriftUtil.getTServerClient(ThriftUtil.java:175) ~[classes/:?]
	at org.apache.accumulo.core.clientImpl.ThriftScanner.close(ThriftScanner.java:586) ~[classes/:?]
	at org.apache.accumulo.core.clientImpl.ScannerIterator.lambda$close$0(ScannerIterator.java:129) ~[classes/:?]
	at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[classes/:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
</pre>

**Comment by milleruntime** [comment] 2022-04-13 13:32
It seems like this IT is just very flaky. I dropped the timeout of 6 minutes and when I run in my IDE (intelliJ) the tests pass. When I run the IT again on the command line, it takes a long time and sometimes fails.

**Comment by DomGarguilo** [comment] 2022-04-13 14:17
I just ran these tests and am also seeing the binary() test timeout too.

**Comment by ctubbsii** [comment] 2022-04-13 16:47
These tests started timing out after #2612 was merged. It's not just these tests that take longer, though... the total build time went from around 4h10m to 5h35m. I'm going to take another look at the changes in #2612 that might have caused this.

**Comment by ctubbsii** [comment] 2022-04-13 17:35
I've confirmed that these timeouts were caused by the client side idle transports timeout being set to `GENERAL_RPC_TIMEOUT` instead of the previously hard-coded 3 seconds. Setting this in the client properties for the SslIT caused the `binary` test to go from 443.3 seconds to 152.6... much much faster.

**Comment by ctubbsii** [comment] 2022-04-13 17:38
I'm trying to decide whether we should change the client-side back to a hard-coded 3 seconds, or if we should just override the default to set it to a low number for MiniAccumuloCluster, or create a new client-side property specifically for this.

**Comment by EdColeman** [comment] 2022-04-13 17:42
what - if any impact would any of the different timeout settings have on existing clients?   From the discussion, it seems that if they are closing (or letting the client close) then there would be no impact - but if it defaulted to a value larger than the 3 seconds, how would that impact them?

Even having a separate, client-side prop that was set to the default - how would someone determine what a "better" value was?

**Comment by ctubbsii** [comment] 2022-04-13 18:51
> what - if any impact would any of the different timeout settings have on existing clients? From the discussion, it seems that if they are closing (or letting the client close) then there would be no impact - but if it defaulted to a value larger than the 3 seconds, how would that impact them?
> 
> Even having a separate, client-side prop that was set to the default - how would someone determine what a "better" value was?

So, I'm not actually sure why the timeout is even making a difference... certainly not that substantial of a difference. The impact is in startup/teardown of new transports... I wouldn't have thought they'd be *that* expensive. But, apparently they are expensive enough to warrant us creating a pool to reuse them, and expensive enough for the JIRA request to make them configurable on the client side.

The fact that performance worsened when the timeout default increased implies the expense we saw was primarily in the shutting down of transports when the client is closed... because a longer timeout means more are still sticking around when the client is closed. I would have expected more performance lost creating new transports, not closing the ones that stuck around. But that's not what we saw in the tests after my change.

So, ultimately, I have no idea how users decide how to optimize this value. What I do know... is that the client side needs to go back to its previous default value, which was 3 seconds. So, I'm creating a separate property so its default is different on the client than on the server. I'm testing that locally now and will have a PR up soon.

**Closed** 2022-04-14 01:59 UTC
Labels: blocker, bug
