### ISSUE TITLE
Merge accumulo-proxy project into accumulo project

### ISSUE THREAD

**Issue by hkeebler** [apache/accumulo#1180] opened 2019-06-04 20:09 UTC
A separate accumulo/proxy project was created to build and test the thrift proxy.  The proxy code needs to be moved into the accumulo project.  There may be some decoupling in the code required.

**Comment by hkeebler** [comment] 2019-06-04 20:13
This looks to be a close fit with the accumulo-proxy module.    I'll start working this.

**Comment by ctubbsii** [comment] 2019-06-05 00:16
@hkeebler The https://github.com/apache/accumulo-proxy repository was created to take what we have in https://github.com/apache/accumulo/tree/master/proxy and separate it into its own (sub-)project within the Accumulo community. I started the work, but did not finish. The goal is to delete it from the main Accumulo builds, so it can live (or die) on its own. I'm not sure what is needed to finish it, but ideally, it should have all the latest updates from https://github.com/apache/accumulo/tree/master/proxy (so that can be deleted) and it should build against the latest Accumulo 2.0 SNAPSHOT (eventually 2.0 proper when that is released).

**Comment by ctubbsii** [comment] 2019-06-05 00:17
The task here should be to delete the proxy/ module.
The task in https://github.com/apache/accumulo-proxy/issues should be to ensure it builds and works over there.

**Comment by hkeebler** [comment] 2019-06-05 11:24
Thank you.  I had it backwards.  Since, the module was more up to date this makes more sense.

**Comment by ctubbsii** [comment] 2019-06-05 16:47
This is a duplicate of #454

**Closed by ctubbsii** 2019-06-05 16:47 UTC
