### ISSUE TITLE
Broken or Flaky test: WatchTheWatchCountIT

### ISSUE THREAD

**Issue by Manno15** [apache/accumulo#2348] opened 2021-11-05 14:32 UTC
**Test name(s)**
 - org.apache.accumulo.test.functional.test

**Describe the failure observed**
This test seems to have been flaky for some time now. Failing in about once every five test runs.

<details>
<summary>WatchTheWatchCountIT would see more than the expected amount of watchers</summary>

```
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 40.766 s <<< FAILURE! - in org.apache.accumulo.test.functional.WatchTheWatchCountIT
[ERROR] org.apache.accumulo.test.functional.WatchTheWatchCountIT.test  Time elapsed: 40.707 s  <<< FAILURE!
java.lang.AssertionError: Expected number of watchers to be contained in (475, 700), but actually was 805
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.apache.accumulo.test.functional.WatchTheWatchCountIT.test(WatchTheWatchCountIT.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   WatchTheWatchCountIT.test:84 Expected number of watchers to be contained in (475, 700), but actually was 805
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

```

</details>

**Testing Environment:**
 - Version of this project: 2.1.0-SNAPSHOT
 - First commit known to fail (or current commit): Unsure of initial commit but fails on the current
 - OS: Pop OS (OS name: Pop!_OS version: 21.04)
 - Java: 11.0.11, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
 - Maven:  3.6.3
 - Other environment details: Fails both in terminal and while running in Intellij

**What have you tried already?**
Reran numerous times and on multiple commits with the same results. 

**Additional context**
N/A

**Comment by EdColeman** [comment] 2021-11-05 15:47
With property store changes this test with either need to change or will be OBE.  I'll look at it when the prop store final PR is ready.

**Comment by Manno15** [comment] 2021-11-05 16:17
> With property store changes this test with either need to change or will be OBE. I'll look at it when the prop store final PR is ready.

I figured it would but I wanted to make sure it was documented.

**Comment by dlmarion** [comment] 2022-01-31 21:37
@ctubbsii increased the timeout in 3183f7accb1c1505e69709e9763e83d1f9bca7d8, this may be OBE.

**Comment by ctubbsii** [comment] 2022-02-01 15:41
This was likely caused by us adding new configuration properties for compaction and other features. It seems fixed for now. It will be fixed further with the ongoing efforts to consolidate the configuration properties in ZK into fewer nodes (will probably be broken in the other direction, too few watches found, but we will address that when the time comes).

**Closed by ctubbsii** 2022-02-01 15:41 UTC
Labels: bug, test
