### ISSUE TITLE
Log recovery can not succeed after failed marker written in recovery directory

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#961] opened 2019-02-14 20:39 UTC
Accumulo version 1.8.1.  When tserver log recovery fails in LogSorter.sort() and a FailedMarkerPath (failed) file is written to the recovery directory, subsequent recoveries fail due to the presence of this file.  In subsequent recovery attempts, when the subdirectories of the recovery root directory are iteratated over in the RecoveryLogReader constructor, the failed marker is interpreted as any other partial results directory and an exception is generated when the underlying data can not be read.  This happens even when a finished marker exists (both were present with the same timestamp - another issue?) because failed comes before finished alphabetically.

Copied from 

https://issues.apache.org/jira/browse/ACCUMULO-4861

**Comment by milleruntime** [comment] 2019-03-20 20:18
@billoley I am trying to replicate this error in a Test.  Was this exception similar to the one you saw for this issue?
<pre>
java.io.FileNotFoundException: File file:/accumulo/server/tserver/target/junit1148327992366485527/manyMaps/failed/data does not exist

	at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:537)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:750)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:527)
	at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:409)
	at org.apache.hadoop.io.SequenceFile$Reader.<init>(SequenceFile.java:1817)
	at org.apache.hadoop.io.MapFile$Reader.createDataFileReader(MapFile.java:455)
	at org.apache.hadoop.io.MapFile$Reader.open(MapFile.java:428)
	at org.apache.hadoop.io.MapFile$Reader.<init>(MapFile.java:398)
	at org.apache.accumulo.tserver.log.RecoveryLogReader.<init>(RecoveryLogReader.java:132)
	at org.apache.accumulo.tserver.log.RecoveryLogReader.<init>(RecoveryLogReader.java:117)
	at org.apache.accumulo.tserver.log.RecoveryLogsReaderTest.testFailed(RecoveryLogsReaderTest.java:191)
</pre>

**Comment by milleruntime** [comment] 2019-03-21 18:54
Better yet, it probably looked more like this:
<pre>
java.lang.RuntimeException: Error recovering tablet +r<< from log files
        at org.apache.accumulo.tserver.tablet.Tablet.<init>(Tablet.java:492)
        at org.apache.accumulo.tserver.TabletServer$AssignmentHandler.run(TabletServer.java:2373)
        at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:35)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: java.io.FileNotFoundException: File does not exist: hdfs://localhost:8020/accumulo/recovery/53b1eda2-197a-4d4d-8690-3d4c615880c5/failed/data
        at org.apache.accumulo.tserver.log.TabletServerLogger.recover(TabletServerLogger.java:568)
        at org.apache.accumulo.tserver.TabletServer.recover(TabletServer.java:3279)
        at org.apache.accumulo.tserver.tablet.Tablet.<init>(Tablet.java:430)
        ... 3 more
Caused by: java.io.FileNotFoundException: File does not exist: hdfs://localhost:8020/accumulo/recovery/53b1eda2-197a-4d4d-8690-3d4c615880c5/failed/data
        at org.apache.hadoop.hdfs.DistributedFileSystem$27.doCall(DistributedFileSystem.java:1444)
        at org.apache.hadoop.hdfs.DistributedFileSystem$27.doCall(DistributedFileSystem.java:1437)
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
        at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1437)
        at org.apache.hadoop.io.SequenceFile$Reader.<init>(SequenceFile.java:1831)
        at org.apache.hadoop.io.MapFile$Reader.createDataFileReader(MapFile.java:460)
        at org.apache.hadoop.io.MapFile$Reader.open(MapFile.java:433)
        at org.apache.hadoop.io.MapFile$Reader.<init>(MapFile.java:403)
        at org.apache.accumulo.tserver.log.RecoveryLogReader.<init>(RecoveryLogReader.java:131)
        at org.apache.accumulo.tserver.log.RecoveryLogsIterator.<init>(RecoveryLogsIterator.java:56)
        at org.apache.accumulo.tserver.log.SortedLogRecovery.findMaxTabletId(SortedLogRecovery.java:105)
        at org.apache.accumulo.tserver.log.SortedLogRecovery.findLogsThatDefineTablet(SortedLogRecovery.java:145)
        at org.apache.accumulo.tserver.log.SortedLogRecovery.recover(SortedLogRecovery.java:309)
        at org.apache.accumulo.tserver.log.TabletServerLogger.recover(TabletServerLogger.java:566)
        ... 5 more
</pre>

I was able to generate this error using uno and just always throwing a Throwable in the LogSorter sort method.

**Comment by billoley** [comment] 2019-03-21 19:30
Yes -- that's the right place in RecoveryLogReader.  Since a "failed" marker doesn't start with _ and isn't "finished" (both of which are skipped via continue), then the RecoveryLogReader tries to treat the failed marker as a parent directory with a data subdirectory.

**Comment by milleruntime** [comment] 2019-03-25 19:47
Fixed in #1048

**Closed by milleruntime** 2019-03-25 19:47 UTC
Labels: blocker, bug, v1.9.3, v2.0.0
