### ISSUE TITLE
New API method in InstanceOperations returns thrift type

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#2983] opened 2022-09-28 21:36 UTC
The following new API method returns a thrift type.  We should avoid returning thrift types in the API unless there is no other alternative.

https://github.com/apache/accumulo/blob/1a3c7c1fc75dcf665946d2d3dcbb36c52528f0f2/core/src/main/java/org/apache/accumulo/core/client/admin/InstanceOperations.java#L103

The new API is also missing a since javadoc tag.

**Comment by milleruntime** [comment] 2022-09-29 15:11
I had seen this but got side tracked. I think the easiest fix would be to just return a `Map<String,String>` for this version, like the other InstanceOperations methods.

**Comment by ctubbsii** [comment] 2022-09-29 15:34
@keith-turner Any insight into why this wasn't caught by apilyzer-maven-plugin?

**Comment by dlmarion** [comment] 2022-09-29 15:34
I have a fix for this.

**Comment by ctubbsii** [comment] 2022-09-29 15:38
> I had seen this but got side tracked. I think the easiest fix would be to just return a `Map<String,String>` for this version, like the other InstanceOperations methods.

We already have a method that returns `Map<String,String>`. It seems the idea for this new method was to return the version, which I'm not sure how that was intended to be used by end users. It may be best to just make this method private, or move it to an internal Impl class.

**Comment by ctubbsii** [comment] 2022-09-29 15:52
> > We already have a method that returns Map<String,String>
> 
> Where are you seeing that? You see another `Map<String,String> getSystemProperties` ?

It's called "getSystemConfiguration"

**Comment by dlmarion** [comment] 2022-09-29 16:15
Thanks. I get confused by our use of props, properties, configuration, etc.

**Closed** 2022-09-29 18:22 UTC
Labels: blocker, bug

**Comment by cshannon** [comment] 2022-09-30 10:37
This change seems to be causing a test failure in PropStoreConfigIT, https://builds.apache.org/job/Accumulo/job/main/lastCompletedBuild/org.apache.accumulo$accumulo-test/testReport/org.apache.accumulo.test.conf/PropStoreConfigIT/modifyInstancePropertiesTest/

I can take a quick look but wanted to point it out

**Comment by cshannon** [comment] 2022-09-30 10:47
I commented in the PR but the two methods actually return different things. One returned just the system properties vs the entire config which is why the test fails. So I think we should bring the getProperties() back but just document how it's different.
