### ISSUE TITLE
IllegalStateException: Active assignment already exists

### ISSUE THREAD

**Issue by mikewalch** [apache/accumulo#547] opened 2018-07-02 22:05 UTC
Encountered this exception while running continuous ingest on 1.9 branch.

```
Thread "tablet assignment 1" died Active assignment already exists for 2;7666c;759a09
	java.lang.IllegalStateException: Active assignment already exists for 2;7666c;759a09
		at org.apache.accumulo.tserver.ActiveAssignmentRunnable.run(ActiveAssignmentRunnable.java:54)
		at org.apache.htrace.wrappers.TraceRunnable.run(TraceRunnable.java:57)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:35)
		at java.lang.Thread.run(Thread.java:748)
```

**Comment by ctubbsii** [comment] 2018-07-12 00:59
Removed 1.9.2 label in prep for RC1, since it's not marked as a blocker. Also not sure if it's still relevant (or if it was found before or after applying the latest round of @keith-turner 's WAL patches).

**Comment by ctubbsii** [comment] 2019-03-25 21:03
@mikewalch Have you seen this lately? Should this be done for 1.9.3?

**Comment by mikewalch** [comment] 2019-03-25 21:07
> @mikewalch Have you seen this lately? Should this be done for 1.9.3?

No but I haven't run continuous ingest lately. I say hold off on it unless it reappears in testing.

**Comment by ctubbsii** [comment] 2019-03-25 22:10
Okay, then I'm bumping it from 1.9.3 so we can prepare for a 1.9.3 release candidate.

**Comment by milleruntime** [comment] 2019-06-17 16:16
@mikewalch do you remember if you ran this using a Muchos cluster?

**Comment by ctubbsii** [comment] 2019-06-17 17:55
@keith-turner ran a successful continuous ingest run for 1.9.3, so I'm inclined to close this as "cannot reproduce". It can always be re-opened if it's seen again.

**Closed by ctubbsii** 2019-06-17 17:55 UTC
Labels: bug, v2.0.0
