### ISSUE TITLE
Exception while running continuous ingest

### ISSUE THREAD

**Issue by mikewalch** [apache/accumulo#563] opened 2018-07-17 15:02 UTC
Encountered this error/exception while running continuous ingest. It looks like it could be a normal/expected behavior.  If so, the exception should stop being thrown and a debug message should be printed instead.
```
2018-07-17 02:52:03,429 [util.NamingThreadFactory] ERROR: Thread "tablet assignment 2" died Active assignment already exists for 2;49999;48ccf
java.lang.IllegalStateException: Active assignment already exists for 2;49999;48ccf
        at org.apache.accumulo.tserver.ActiveAssignmentRunnable.run(ActiveAssignmentRunnable.java:54)
        at org.apache.htrace.wrappers.TraceRunnable.run(TraceRunnable.java:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:35)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by ctubbsii** [comment] 2018-07-17 15:21
This is a duplicate of #547

**Closed by ctubbsii** 2018-07-17 15:21 UTC
Labels: bug, duplicate, v1.9.3
