### ISSUE TITLE
Improve verification in TabletManagementIteratorIT

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#4231] opened 2024-02-05 22:03 UTC
This is an existing problem with this test.  The test could do more than just verify a count, it could verify the ManagementActions and extents returned are what is expected.  I can open an issue about this.

_Originally posted by @keith-turner in https://github.com/apache/accumulo/pull/4229#discussion_r1478954146_

**Comment by ArbaazKhan1** [comment] 2024-03-25 17:50
I think this is being addressed in [issue4344](https://github.com/apache/accumulo/issues/4344)

**Comment by dlmarion** [comment] 2024-04-25 12:14
Thanks @ArbaazKhan1 , this does look like a dupe of #4344. Closing this as the other issue has more detail.

**Closed by dlmarion** 2024-04-25 12:14 UTC
