### ISSUE TITLE
tservers hosting metadata could not complete shutdown

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#3512] opened 2023-06-21 21:37 UTC
User reports that [the issue reported in #3368] has been observed again. They don't know if it is the same reason.
These are tservers that are exclusively handling accumulo.metadata tablets. They were stuck spamming the following messages:

```
SessionManager INFO : Closing idle session from user=!SYSTEM, client=<manager node>
Tablet DEBUG: Waiting to completeClose for ..., 0 writes 1 scans
```
This was seen with ACCUMULO 2.1.1-RC2 (which was released as 2.1.1)

_Originally posted by @ivakegg in https://github.com/apache/accumulo/issues/3368#issuecomment-1601322659_

**Comment by keith-turner** [comment] 2023-06-26 16:32
While examining the code looking for causes I found one possible candidate cause for this.  It may not be the cause of this problem, but it needs to be fixed.  Scan sessions register a cleanup call if the session is not accessed in a certain amount of time.  This cleanup code calls session.cleanUp which returns a boolean, however that return value is not checked.  When it returns false the session was not cleaned up and clean up needs to be attempted again later.  Below is the line where the return value was not checked.

https://github.com/apache/accumulo/blob/260fde4370c06a4059fd62b5658124d61532d729/server/tserver/src/main/java/org/apache/accumulo/tserver/session/SessionManager.java#L285

I will work on a fix for this.

**Comment by keith-turner** [comment] 2023-06-28 17:25
I may have been able to reproduce this. I was running the following in jshell because I suspected an issue with isolated scans.  I currently have a tablet stuck in close waiting to scan. I am investigating the stuck tablet.

```java
        client.tableOperations().create("foo");

        try(var writer = client.createBatchWriter("foo")) {
            for(int i = 0; i < 1000000; i++) {
                Mutation m = new Mutation(String.format("%08d", i));
                m.put("","","");
                writer.addMutation(m);
            }
        }

        client.tableOperations().flush("foo",null,null,true);

        Runnable task = new Runnable() {
            @Override
            public void run() {
                while(true) {
                    try (var scanner = new IsolatedScanner(client.createScanner("foo"))) {
                        // TODO maybe do not close scanner?  The following limit was placed on the stream to 
                        //  avoid reading all the data possibly leaving a scan session active on the tserver
                        System.out.println(new Date()+" "+scanner.stream().limit(500000).count());
                    } catch (Exception e) {
                        e.printStackTrace();
                        break;
                    }
                }
            }
        };

        ExecutorService service = Executors.newFixedThreadPool(10);
        for(int i =0; i< 10; i++){
          service.execute(task);
        };

        // do periodic splits to force tablet to close.. TODO eventually splitting tablet we are not scanning above
        for(int i = 0; i < 1000000; i+=1000) {
            String split = String.format("%08d", i);
            client.tableOperations().addSplits("foo", new TreeSet<>(List.of(new Text(split))));
            System.out.println(new Date()+" added split "+split);
            Thread.sleep(500);
        }
```

**Comment by jmark99** [comment] 2023-06-29 14:01
@keith-turner asked to see if others could replicate his error by running the code in the previous comment. I was able to do so. Afterward, he asked for checks to be put in the code when the session cleanup method was called. I added checks in three locations within the `SessionManager` and re-ran the test. Doing so indicated that the `session.close()` method returned false when called within `removeSession` around line 212.

The modified code was as follows:

```
      if (doCleanup) {
        boolean cleanup = session.cleanup();
        if (!cleanup) {
          log.info(">>>> session.cleanup() false around line 212");
        }
      }
```

The following line appears in tserver.log:

`2023-06-29T09:35:30,313 [session.SessionManager] INFO : >>>> session.cleanup() false around line 212`

I allowed the jshell session to run about 11 minutes before force quitting. The output was similar to the lines below:

```
Thu Jun 29 09:35:29 EDT 2023 added split 00014000                                                                                                                          
Thu Jun 29 09:35:14 EDT 2023 500000                                                                                                                                        
Thu Jun 29 09:35:14 EDT 2023 500000                                                                                                                                        
2023-06-29T09:37:31,344 [admin.TableOperations] WARN : Having difficulty locating hosting tabletserver for split 00015000 on table foo. Seen 5 failures.                   
2023-06-29T09:37:38,735 [admin.TableOperations] WARN : Having difficulty locating hosting tabletserver for split 00015000 on table foo. Seen 50 failures.                  
2023-06-29T09:37:45,736 [admin.TableOperations] WARN : Having difficulty locating hosting tabletserver for split 00015000 on table foo. Seen 100 failures.                 
2023-06-29T09:37:52,872 [admin.TableOperations] WARN : Having difficulty locating hosting tabletserver for split 00015000 on table foo. Seen 150 failures.  
...
2023-06-29T09:45:58,101 [admin.TableOperations] WARN : Having difficulty locating hosting tabletserver for split 00015000 on table foo. Seen 3650 failures.
2023-06-29T09:46:05,042 [admin.TableOperations] WARN : Having difficulty locating hosting tabletserver for split 00015000 on table foo. Seen 3700 failures.
2023-06-29T09:46:12,024 [admin.TableOperations] WARN : Having difficulty locating hosting tabletserver for split 00015000 on table foo. Seen 3750 failures.

```

**Comment by keith-turner** [comment] 2023-06-29 18:49
One way to fix this is to have single method like the following in SessionManager that is used for all session cleanup.

```java
void cleanup(Collection<Session> sessions){
 for(var session : sessions){
    if(!session.cleanup()){
        // Queue session for defered clean up at later time.  This could be done by scheduling a 
        // task to run later or adding it a collection that is periodically inspected by a scheduled 
        // task.  The sweep() method in session manager method handles deferred cleanup for 
        // itself it, this could be generalized for the entire class.  The sweep() method is already
        // called periodically.
   }
}
```

**Comment by dlmarion** [comment] 2023-06-29 19:36
Looking at the implementations of `Session.cleanup()`, only `SingleScanSession` and `SummarySession` can return `false`. `SummarySession` just returns the return value of `Future.cancel(true)`, which I think in most cases will end cancelling the future. The `SingleScanSession` case is more complicated as it calls `Scanner.close` which will return `false` if it doesn't obtain a lock within 10ms.

**Comment by dlmarion** [comment] 2023-06-29 20:02
Should `Scanner.close` call `isolatedDataSource.interrupt()` before trying to obtain the `scannerSemaphore` ?

**Comment by keith-turner** [comment] 2023-06-29 21:25
> Should Scanner.close call isolatedDataSource.interrupt() before trying to obtain the scannerSemaphore ?

I think the interruptFlag that it does set to true is also passed to the scanner data source when its created, so should be that same.

**Comment by dlmarion** [comment] 2023-06-30 18:19
@keith-turner @jmark99 - I turned your jshell test into an IT in https://github.com/dlmarion/accumulo/commit/cfb428d8a7bc351720685fd6353d140171fff5ba. I was able to reproduce the tablet server shutting down, but I think the cause may be different. What I'm seeing in the logs is that the Manager requests that the root and test table tablet be unloaded from the tablet server. The TabletGroupWatcher for the metadata table however never requests that the metadata table tablet be unloaded. The TabletGroupWatcher for the metadata table appears to be waiting at MetadataTableScanner.hasNext(), possibly due to the root tablet being unloaded?

Anyway, I'm not sure that what I'm seeing is related to this specific issue, but I wanted to provide the information just in case.

**Comment by keith-turner** [comment] 2023-07-06 00:58
> I was able to reproduce the tablet server shutting down, but I think the cause may be different. What I'm seeing in the logs is that the Manager requests that the root and test table tablet be unloaded from the tablet server. 

That sounds like an additional bug possibly, I opened as #3569 as a fix for the problem of sessions not being cleaned up.  We should not close this issue for #3569 w/o figuring out the TGW problem or opening an issue for it.

**Comment by ctubbsii** [comment] 2023-07-11 05:39
With #3571, it looks like this can be closed. Is there something keeping this issue open?

**Comment by dlmarion** [comment] 2023-07-27 16:39
I talked with @ivakegg , he said we are good to close this and they will open a new issue if needed.

**Closed by dlmarion** 2023-07-27 16:39 UTC
Labels: bug
