### ISSUE TITLE
Add documentation about auditing to user manual

### ISSUE THREAD

**Issue by DonResnik** [apache/accumulo#1136] opened 2019-04-29 00:12 UTC
Brought over from Jira 

https://issues.apache.org/jira/projects/ACCUMULO/issues/ACCUMULO-4635

Right now the user manual makes no mention of our auditing capabilities. We should cover operational concerns:
Where does the audit log go? Can I change it?
What Accumulo actions get audited? Can I change it?
What information is included in the audit log entries? Can I change it?

**Comment by DonResnik** [comment] 2019-04-29 00:12
I am going to work on this

**Comment by ctubbsii** [comment] 2019-04-30 02:05
This issue should be on apache/accumulo-website instead. Since there's already a PR there, I'm closing this as duplicate of apache/accumulo-website#177

**Closed by ctubbsii** 2019-04-30 02:05 UTC
